// ignore_for_file: file_names

import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_English'   : {
      "Captains are busy" : "Captains are busy",
      "Find a driver" : "Find a driver",
      "City to city" : "City to city",
      "From" : "From",
      "To" : "To",
      "Departure date" : "Departure date",
      "Departure time" : "Departure time",
      "Done" : "Done",
      "Skip" : "Skip",
      "Next" : "Next",
      "When" : "When",
      "Number of passengers" : "Number of passengers",
      "Set your price" : "Set your price",
      "We charge no commission. Full" : "We charge no commission. Full",
      "amount goes to the captain" : "amount goes to the captain",
      "Higher the price,higher the chance of" : "Higher the price,higher the chance of",
      "getting a ride" : "getting a ride",
      "Automatically accept the nearest driver for your fare" : "Automatically accept the nearest driver for your fare",
      "Offer your fare" : "Offer your fare",
      "Comments" : "Comments",
      "How many of you will go?" : "How many of you will go?",
      "Captain on the way" : "Captain on the way",
      "Captain has arrived" : "Captain has arrived",
      "Heading to the destination" : "Heading to the destination",
      "Start your order with PIN" : "Start your order with PIN",
      "Pickup From" : "Pickup From",
      "Trip Details" : "Trip Details",
      "Rating" : "Rating",
      "Trips" : "Trips",
      "Joined" : "Joined",
      "Language" : "Language",
      "Preference" : "Preference",
      "Choose a driver" : "Choose a driver",
      "Driver can offer their fare and time" : "Driver can offer their fare and time",
      "Decline" : "Decline",
      "Accept" : "Accept",
      "Drop to" : "Drop to",
      "Faq List" : "Faq List",
      "CONTINUE" : "CONTINUE",
      "Payment Getway Method" : "Payment Getway Method",
      "All coupons" : "All coupons",
      "Best Coupon" : "Best Coupon",
      "Coupon Code: " : "Coupon Code: ",
      "Coupon Amount: " : "Coupon Amount: ",
      "Minimum Amount: " : "Minimum Amount: ",
      "Ex Date: " : "Ex Date: ",
      "Remove" : "Remove",
      "Apply coupons" : "Apply coupons",
      "Coupon" : "Coupon",
      "Coupon applied" : "Coupon applied",
      "Try Again" : "Try Again",
      "Cancel" : "Cancel",
      "Home" : "Home",
      "My Ride" : "My Ride",
      "Wallet" : "Wallet",
      "Profile" : "Profile",
      "Faq" : "Faq",
      "Refer and earn" : "Refer and earn",
      "Notifications" : "Notifications",
      "Your Current Location" : "Your Current Location",
      "Close" : "Close",
      "Searching for you on the map..." : "Searching for you on the map...",
      "💡Raise the fare, increase your chances." : "💡Raise the fare, increase your chances.",
      "Automatically book the nearest driver for" : "Automatically book the nearest driver for",
      "Cancel Request" : "Cancel Request",
      "cancel" : "cancel",
      "Completed" : "Completed",
      "Invoice" : "Invoice",
      "Rate your ride" : "Rate your ride",
      "Pickup" : "Pickup",
      "Destination" : "Destination",
      "RIDE DETAIL" : "RIDE DETAIL",
      "Ride Type :" : "Ride Type :",
      "Car Type :" : "Car Type :",
      "hours / minit :" : "hours / minit :",
      "Date & Time :" : "Date & Time :",
      "PAYMENT" : "PAYMENT",
      "Ride Fair :" : "Ride Fair :",
      "Promo :" : "Promo :",
      "PlatformFee :" : "PlatformFee :",
      "Weather Price :" : "Weather Price :",
      "Total :" : "Total :",
      "My Rides" : "My Rides",
      "Upcoming" : "Upcoming",
      "Cancelled" : "Cancelled",
      "Notification" : "Notification",
      "No new notifications" : "No new notifications",
      "Looks like you haven't received any notification" : "Looks like you haven't received any notification",
      "Allow Notifications and on-ride alerts" : "Allow Notifications and on-ride alerts",
      "Real-time Captain updates" : "Real-time Captain updates",
      "Get notified about captain`s allocation, arrival and more" : "Get notified about captain`s allocation, arrival and more",
      "Be the first to know about our offers and new features" : "Be the first to know about our offers and new features",
      "Allow" : "Allow",
      "Maybe, later" : "Maybe, later",
      "Location permission not enabled" : "Location permission not enabled",
      "Sharing Location permission helps us improve your ride booking and pickup experience" : "Sharing Location permission helps us improve your ride booking and pickup experience",
      "Allow Permission" : "Allow Permission",
      "Enter pickup manually" : "Enter pickup manually",
      "Drop" : "Drop",
      "Drop location" : "Drop location",
      "Select on map" : "Select on map",
      "Add a destination" : "Add a destination",
      "Update" : "Update",
      "My Profile" : "My Profile",
      "Name" : "Name",
      "Email" : "Email",
      "Password" : "Password",
      "Refer your friends" : "Refer your friends",
      "& Earn Coins!" : "& Earn Coins!",
      "Invite all your friend to " : "Invite all your friend to ",
      "ZippyGo" : "ZippyGo",
      "Your referred person gets " : "Your referred person gets ",
      "coins when they sign up using your code" : " coins when they sign up using your code",
      "and you receive " : "and you receive ",
      "coins when the person you referred purchases a membership." : " coins when the person you referred purchases a membership.",
      "Start inviting friends today and enjoy the benefits together!" : "Start inviting friends today and enjoy the benefits together!",
      "Refer a Friend" : "Refer a Friend",
      "Help" : "Help",
      "H" : "H",
      "RIDE COMPLETED" : "RIDE COMPLETED",
      "Select a payment method to pay" : "Select a payment method to pay",
      "Total trip fare" : "Total trip fare",
      "Ride Charges" : "Ride Charges",
      "Discount" : "Discount",
      "Whether Charge" : "Whether Charge",
      "Platform fee" : "Platform fee",
      "AMOUNT TO BE PAID" : "AMOUNT TO BE PAID",
      "Payment Gateway Method" : "Payment Gateway Method",
      "Total Balance" : "Total Balance",
      "Add Wallet Amount" : "Add Wallet Amount",
      "Enter Amount" : "Enter Amount",
      "Select Payment Method" : "Select Payment Method",
      "Enter Amount!!!" : "Enter Amount!!!",
      "Top-up" : "Top-up",
      "Join Our App and Make a Difference:" : "Join Our App and Make a Difference:",
      "Donate Today!" : "Donate Today!",
      "Invite friend" : "Invite friend",
      "Transaction History" : "Transaction History",
      "Debit" : "Debit",
      "Creadit" : "Creadit",
      "Welcome to Your ZippyGo Ride!" : "Welcome to Your ZippyGo Ride!",
      "Your Journey, Just a Tap Away" : "Your Journey, Just a Tap Away",
      "Wherever You Go, We’re Here" : "Wherever You Go, We’re Here",
      "Book a ride in just a few taps and reach your destination comfortably" : "Book a ride in just a few taps and reach your destination comfortably",
      "Experience fast, reliable, and safe rides with ease." : "Experience fast, reliable, and safe rides with ease.",
      "Find a ride quickly and enjoy your journey hassle-free" : "Find a ride quickly and enjoy your journey hassle-free",
      "Phone Number" : "Phone Number",
      "By clicking Continue.you agree tp our " : "By clicking Continue.you agree tp our ",
      "T&Cs" : "T&Cs",
      "Continue" : "Continue",
      "Forget Password ?" : "Forget Password ?",
      "Enter Mobile Number...!!!" : "Enter Mobile Number...!!!",
      "Forgot Password ?" : "Forgot Password ?",
      "Milk made modern!" : "Milk made modern!",
      "Our app combines the convenience of technology with the tradition of the milkman" : "Our app combines the convenience of technology with the tradition of the milkman",
      "Never miss a delivery again!" : "Never miss a delivery again!",
      "With our app, you'll receive real-time notifications about your milk deliveries" : "With our app, you'll receive real-time notifications about your milk deliveries",
      "Milk at your fingertips!" : "Milk at your fingertips!",
      "order fresh milk and dairy products for delivery straight to your doorstep" : "order fresh milk and dairy products for delivery straight to your doorstep",
      "Get Started" : "Get Started",
      "Step 1/3" : "Step 1/3",
      "Let's get you trip-ready!" : "Let's get you trip-ready!",
      "Step 1/2" : "Step 1/2",
      "Got an OTP?" : "Got an OTP?",
      "Step 2/2" : "Step 2/2",
      "Just one last thing" : "Just one last thing",
      "Full Name" : "Full Name",
      "email" : "email",
      "Referral code(optional)" : "Referral code(optional)",
      "Referral code" : "Referral code",
      "Let's go!" : "Let's go!",
      "No Chat Found!" : "No Chat Found!",
      "Currently you don’t have chat." : "Currently you don’t have chat.",
      "Say Something..." : "Say Something...",
      "Reject" : "Reject",
      "How much time do you need?" : "How much time do you need?",
      "Leave now" : "Leave now",
      "Leave later" : "Leave later",
      "Date and Time" : "Date and Time",
      "Starting at" : "Starting at",
      "Choose a ride" : "Choose a ride",
      // "" : "",
    },
    'en_spanse'    : {
      "Captains are busy" : "Los capitanes están ocupados",
      "Find a driver" : "Encuentra un conductor",
      "City to city" : "De ciudad a ciudad",
      "From" : "Desde",
      "To" : "Hasta",
      "Departure date" : "Fecha de salida",
      "Departure time" : "Hora de salida",
      "Done" : "Hecho",
      "Skip" : "Saltar",
      "Next" : "Siguiente",
      "When" : "Cuándo",
      "Number of passengers" : "Número de pasajeros",
      "Set your price" : "Establece tu precio",
      "We charge no commission. Full" : "No cobramos comisión. El importe",
      "amount goes to the captain" : "completo va al capitán",
      "Higher the price,higher the chance of" : "Cuanto más alto sea el precio, mayor será la posibilidad de",
      "getting a ride" : "conseguir un viaje",
      "Automatically accept the nearest driver for your fare" : "Acepta automáticamente al conductor más cercano para tu tarifa",
      "Offer your fare" : "Ofrece tu tarifa",
      "Comments" : "Comentarios",
      "How many of you will go?" : "¿Cuántos de ustedes irán?",
      "Captain on the way" : "Capitán en camino",
      "Captain has arrived" : "El capitán ha llegado",
      "Heading to the destination" : "Se dirige al destino",
      "Start your order with PIN" : "Comienza tu pedido con PIN",
      "Pickup From" : "Recogida desde",
      "Trip Details" : "Detalles del viaje",
      "Rating" : "Calificación",
      "Trips" : "Viajes",
      "Joined" : "Unidos",
      "Language" : "Idioma",
      "Preference" : "Preferencia",
      "Choose a driver" : "Selecciona un conductor",
      "Driver can offer their fare and time" : "El conductor puede ofrecer su tarifa y horario",
      "Decline" : "Rechazar",
      "Accept" : "Aceptar",
      "Drop to" : "Retirar a",
      "Faq List" : "Lista de preguntas frecuentes",
      "CONTINUE" : "CONTINUAR",
      "Payment Getway Method" : "Método de pago Getway",
      "All coupons" : "Todos los cupones",
      "Best Coupon" : "Mejor cupón",
      "Coupon Code: " : "Código de cupón:",
      "Coupon Amount: " : "Monto del cupón:",
      "Minimum Amount: " : "Monto mínimo:",
      "Ex Date: " : "Fecha de vencimiento:",
      "Remove" : "Eliminar",
      "Apply coupons" : "Aplicar cupones",
      "Coupon" : "Cupón",
      "Coupon applied" : "Cupón aplicado",
      "Try Again" : "Intenta nuevamente",
      "Cancel" : "Cancelar",
      "Home" : "Inicio",
      "My Ride" : "Mi viaje",
      "Wallet" : "Billetera",
      "Profile" : "Perfil",
      "Faq" : "Preguntas frecuentes",
      "Refer and earn" : "Recomienda y gana",
      "Notifications" : "Notificaciones",
      "Your Current Location" : "Tu ubicación actual",
      "Close" : "Cerrar",
      "Searching for you on the map..." : "Te buscamos en el mapa...",
      "💡Raise the fare, increase your chances." : "💡Aumenta la tarifa, aumenta tus posibilidades.",
      "Automatically book the nearest driver for" : "Reserva automáticamente el conductor más cercano para",
      "Cancel Request" : "Cancelar solicitud",
      "cancel" : "Cancelar",
      "Completed" : "Completado",
      "Invoice" : "Factura",
      "Rate your ride" : "Califica tu viaje",
      "Pickup" : "Recogida",
      "Destination" : "Destino",
      "RIDE DETAIL" : "DETALLE DEL VIAJE",
      "Ride Type :" : "Tipo de viaje:",
      "Car Type :" : "Tipo de coche:",
      "hours / minit :" : "horas/minuto:",
      "Date & Time :" : "Fecha y hora:",
      "PAYMENT" : "PAGO",
      "Ride Fair :" : "Valor justo del viaje:",
      "Promo :" : "Promoción:",
      "PlatformFee :" : "Tarifa de plataforma:",
      "Weather Price :" : "Precio del tiempo:",
      "Total :" : "Total:",
      "My Rides" : "Mis viajes",
      "Upcoming" : "Próximos",
      "Cancelled" : "Cancelado",
      "Notification" : "Notificación",
      "No new notifications" : "No hay notificaciones nuevas",
      "Looks like you haven't received any notification" : "Parece que no has recibido ninguna notificación",
      "Allow Notifications and on-ride alerts" : "Permitir notificaciones y alertas durante el viaje",
      "Real-time Captain updates" : "Actualizaciones del capitán en tiempo real",
      "Get notified about captain`s allocation, arrival and more" : "Recibe notificaciones sobre la asignación del capitán, la llegada y más",
      "Be the first to know about our offers and new features" : "Sé el primero en conocer nuestras ofertas y nuevas funciones",
      "Allow" : "Permitir",
      "Maybe, later" : "Quizás, más tarde",
      "Location permission not enabled" : "El permiso de ubicación no está habilitado",
      "Sharing Location permission helps us improve your ride booking and pickup experience" : "Compartir el permiso de ubicación nos ayuda a mejorar tu experiencia de reserva y recogida de viajes",
      "Allow Permission" : "Permitir permiso",
      "Enter pickup manually" : "Ingresa la recogida manualmente",
      "Drop" : "Dejar",
      "Drop location" : "Ubicación de entrega",
      "Select on map" : "Selecciona en el mapa",
      "Add a destination" : "Agrega un destino",
      "Update" : "Actualizar",
      "My Profile" : "Mi Perfil",
      "Name" : "Nombre",
      "Email" : "Correo electrónico",
      "Password" : "Contraseña",
      "Refer your friends" : "Recomiende a sus amigos",
      "& Earn Coins!" : "¡y gane monedas!",
      "Invite all your friend to " : "Invite a todos sus amigos a",
      "ZippyGo" : "ZippyGo",
      "Your referred person gets " : "La persona que usted recomendó recibe",
      " coins when they sign up using your code" : "monedas cuando se registra con su código",
      "and you receive " : "y usted recibe",
      " coins when the person you referred purchases a membership." : "monedas cuando la persona que recomendó compra una membresía.",
      "Start inviting friends today and enjoy the benefits together!" : "¡Comience a invitar amigos hoy y disfruten de los beneficios juntos!",
      "Refer a Friend" : "Recomiende a un amigo",
      "Help" : "Ayuda",
      "H" : "H",
      "RIDE COMPLETED" : "VIAJE COMPLETADO",
      "Select a payment method to pay" : "Seleccione un método de pago para pagar",
      "Total trip fare" : "Tarifa total del viaje",
      "Ride Charges" : "Cargos del viaje",
      "Discount" : "Descuento",
      "Whether Charge" : "Si se cobra",
      "Platform fee" : "Tarifa de la plataforma",
      "AMOUNT TO BE PAID" : "MONTO A PAGAR",
      "Payment Gateway Method" : "Método de pasarela de pago",
      "Total Balance" : "Saldo total",
      "Add Wallet Amount" : "Agregar monto a la billetera",
      "Enter Amount" : "Ingrese el monto",
      "Select Payment Method" : "Seleccione el método de pago",
      "Enter Amount!!!" : "¡Ingrese el monto!",
      "Top-up" : "Recarga",
      "Join Our App and Make a Difference:" : "Únase a nuestra aplicación y haga la diferencia:",
      "Donate Today!" : "¡Done hoy!",
      "Invite friend" : "Invitar a un amigo",
      "Transaction History" : "Historial de transacciones",
      "Debit" : "Débito",
      "Creadit" : "Crédito",
      "Welcome to Your ZippyGo Ride!" : "¡Bienvenido a su viaje ZippyGo!",
      "Your Journey, Just a Tap Away" : "Tu viaje, a un toque de distancia",
      "Wherever You Go, We’re Here" : "Adondequiera que vayas, estamos aquí",
      "Book a ride in just a few taps and reach your destination comfortably" : "Reserva un viaje con solo unos toques y llega a tu destino cómodamente",
      "Experience fast, reliable, and safe rides with ease." : "Disfruta de viajes rápidos, confiables y seguros con facilidad.",
      "Find a ride quickly and enjoy your journey hassle-free" : "Encuentra un viaje rápidamente y disfruta de tu viaje sin problemas",
      "Phone Number" : "Número de teléfono",
      "By clicking Continue.you agree tp our " : "Al hacer clic en Continuar, aceptas nuestros",
      "T&Cs" : "Términos y condiciones",
      "Continue" : "Continuar",
      "Forget Password ?" : "¿Olvidaste tu contraseña?",
      "Enter Mobile Number...!!!" : "¡Ingresa tu número de teléfono móvil...!!!",
      "Forgot Password ?" : "¿Olvidaste tu contraseña?",
      "Milk made modern!" : "¡La leche se moderniza!",
      "Our app combines the convenience of technology with the tradition of the milkman" : "Nuestra aplicación combina la comodidad de la tecnología con la tradición del lechero",
      "Never miss a delivery again!" : "¡No te pierdas nunca más una entrega!",
      "With our app, you'll receive real-time notifications about your milk deliveries" : "Con nuestra aplicación, recibirás notificaciones en tiempo real sobre tus entregas de leche",
      "Milk at your fingertips!" : "¡Leche a tu alcance!",
      "order fresh milk and dairy products for delivery straight to your doorstep" : "Pide leche fresca y productos lácteos para que te los entreguen directamente en tu puerta",
      "Get Started" : "Comienza",
      "Step 1/3" : "Paso 1/3",
      "Let's get you trip-ready!" : "¡Preparémonos para el viaje!",
      "Step 1/2" : "Paso 1/2",
      "Got an OTP?" : "¿Tienes una contraseña de un solo uso?",
      "Step 2/2" : "Paso 2/2",
      "Just one last thing" : "Solo una última cosa",
      "Full Name" : "Nombre completo",
      "email" : "Correo electrónico",
      "Referral code(optional)" : "Código de referencia (opcional)",
      "Referral code" : "Código de referencia",
      "Let's go!" : "¡Vamos!",
      "No Chat Found!" : "¡No se encontró ningún chat!",
      "Currently you don’t have chat." : "Actualmente no tienes chat.",
      "Say Something..." : "Di algo...",
      "Reject" : "Rechazar",
      "How much time do you need?" : "¿Cuánto tiempo necesitas?",
      "Leave now" : "Salir ahora",
      "Leave later" : "Salir más tarde",
      "Date and Time" : "Fecha y hora",
      "Starting at" : "Comienza en",
      "Choose a ride" : "Elige un viaje",
    },
    'ur_arabic'    : {
      "Captains are busy" : "القادة مشغولون",
      "Find a driver" : "ابحث عن سائق",
      "City to city" : "من مدينة إلى مدينة",
      "From" : "من",
      "To" : "إلى",
      "Departure date" : "تاريخ المغادرة",
      "Departure time" : "وقت المغادرة",
      "Done" : "تم",
      "Skip" : "تخطي",
      "Next" : "التالي",
      "When" : "متى",
      "Number of passengers" : "عدد الركاب",
      "Set your price" : "حدد السعر",
      "We charge no commission. Full" : "لا نفرض أي عمولة. يذهب المبلغ",
      "amount goes to the captain" : "الكامل إلى القائد",
      "Higher the price,higher the chance of" : "كلما ارتفع السعر، زادت فرصة",
      "getting a ride" : "الحصول على رحلة",
      "Automatically accept the nearest driver for your fare" : "اقبل تلقائيًا أقرب سائق مقابل أجرة",
      "Offer your fare" : "اعرض أجرة",
      "Comments" : "التعليقات",
      "How many of you will go?" : "كم منكم سيذهب؟",
      "Captain on the way" : "الكابتن في الطريق",
      "Captain has arrived" : "لقد وصل الكابتن",
      "Heading to the destination" : "متجه إلى الوجهة",
      "Start your order with PIN" : "ابدأ طلبك باستخدام رقم التعريف الشخصي (PIN)",
      "Pickup From" : "الاستلام من",
      "Trip Details" : "تفاصيل الرحلة",
      "Rating" : "التقييم",
      "Trips" : "الرحلات",
      "Joined" : "تم الانضمام",
      "Language" : "اللغة",
      "Preference" : "التفضيل",
      "Choose a driver" : "اختر سائقًا",
      "Driver can offer their fare and time" : "يمكن للسائق تقديم أجرة ووقت",
      "Decline" : "رفض",
      "Accept" : "قبول",
      "Drop to" : "إسقاط إلى",
      "Faq List" : "قائمة الأسئلة الشائعة",
      "CONTINUE" : "متابعة",
      "Payment Getway Method" : "طريقة الدفع Getway",
      "All coupons" : "جميع القسائم",
      "Best Coupon" : "أفضل قسيمة",
      "Coupon Code: " : "رمز القسيمة:",
      "Coupon Amount: " : "مبلغ القسيمة:",
      "Minimum Amount: " : "الحد الأدنى للمبلغ:",
      "Ex Date: " : "تاريخ انتهاء الصلاحية:",
      "Remove" : "إزالة",
      "Apply coupons" : "تطبيق القسائم",
      "Coupon" : "القسيمة",
      "Coupon applied" : "القسيمة المطبقة",
      "Try Again" : "حاول مرة أخرى",
      "Cancel" : "إلغاء",
      "Home" : "الصفحة الرئيسية",
      "My Ride" : "رحلتي",
      "Wallet" : "المحفظة",
      "Profile" : "الملف الشخصي",
      "Faq" : "الأسئلة الشائعة",
      "Refer and earn" : "أحل واكسب",
      "Notifications" : "الإشعارات",
      "Your Current Location" : "موقعك الحالي",
      "Close" : "إغلاق",
      "Searching for you on the map..." : "البحث عنك على الخريطة...",
      "💡Raise the fare, increase your chances." : "💡ارفع الأجرة، وزد من فرصك.",
      "Automatically book the nearest driver for" : "احجز تلقائيًا أقرب سائق لـ",
      "Cancel Request" : "إلغاء الطلب",
      "cancel" : "إلغاء",
      "Completed" : "مكتمل",
      "Invoice" : "الفاتورة",
      "Rate your ride" : "قيم رحلتك",
      "Pickup" : "الاستلام",
      "Destination" : "الوجهة",
      "RIDE DETAIL" : "تفاصيل الرحلة",
      "Ride Type :" : "نوع الرحلة:",
      "Car Type :" : "نوع السيارة:",
      "hours / minit :" : "ساعات/دقائق:",
      "Date & Time :" : "التاريخ والوقت:",
      "PAYMENT" : "الدفع",
      "Ride Fair :" : "معرض الرحلة:",
      "Promo :" : "العرض الترويجي:",
      "PlatformFee :" : "رسوم المنصة:",
      "Weather Price :" : "سعر الطقس:",
      "Total :" : "الإجمالي:",
      "My Rides" : "رحلاتي",
      "Upcoming" : "المقبلة",
      "Cancelled" : "الملغاة",
      "Notification" : "الإشعارات",
      "No new notifications" : "لا توجد إشعارات جديدة",
      "Looks like you haven't received any notification" : "يبدو أنك لم تتلق أي إشعارات",
      "Allow Notifications and on-ride alerts" : "السماح بالإشعارات والتنبيهات أثناء الرحلة",
      "Real-time Captain updates" : "تحديثات القبطان في الوقت الفعلي",
      "Get notified about captain`s allocation, arrival and more" : "احصل على إشعارات حول تخصيص القبطان ووصوله والمزيد",
      "Be the first to know about our offers and new features" : "كن أول من يعرف بعروضنا والميزات الجديدة",
      "Allow" : "السماح",
      "Maybe, later" : "ربما، لاحقًا",
      "Location permission not enabled" : "إذن الموقع غير ممكّن",
      "Sharing Location permission helps us improve your ride booking and pickup experience" : "مشاركة إذن الموقع يساعدنا في تحسين حجز رحلتك وتجربة الاستلام",
      "Allow Permission" : "السماح بالإذن",
      "Enter pickup manually" : "إدخال الاستلام يدويًا",
      "Drop" : "التسليم",
      "Drop location" : "موقع التسليم",
      "Select on map" : "حدد على الخريطة",
      "Add a destination" : "أضف وجهة",
      "Update" : "تحديث",
      "My Profile" : "My الملف الشخصي",
      "Name" : "الاسم",
      "Email" : "البريد الإلكتروني",
      "Password" : "كلمة المرور",
      "Refer your friends" : "أحل أصدقاءك",
      "& Earn Coins!" : "& اربح عملات!",
      "Invite all your friend to " : "ادعُ جميع أصدقائك إلى",
      "ZippyGo" : "ZippyGo",
      "Your referred person gets " : "يحصل الشخص الذي أحلته على",
      " coins when they sign up using your code" : "عملات عند التسجيل باستخدام الكود الخاص بك",
      "and you receive " : "وتتلقى",
      " coins when the person you referred purchases a membership." : "عملات عندما يشتري الشخص الذي أحلته عضوية.",
      "Start inviting friends today and enjoy the benefits together!" : "ابدأ في دعوة الأصدقاء اليوم واستمتع بالمزايا معًا!",
      "Refer a Friend" : "أحل صديقًا",
      "Help" : "المساعدة",
      "H" : "H",
      "RIDE COMPLETED" : "اكتملت الرحلة",
      "Select a payment method to pay" : "حدد طريقة الدفع للدفع",
      "Total trip fare" : "إجمالي أجرة الرحلة",
      "Ride Charges" : "رسوم الرحلة",
      "Discount" : "الخصم",
      "Whether Charge" : "سواء كانت رسومًا",
      "Platform fee" : "رسوم المنصة",
      "AMOUNT TO BE PAID" : "المبلغ المطلوب دفعه",
      "Payment Gateway Method" : "طريقة بوابة الدفع",
      "Total Balance" : "إجمالي الرصيد",
      "Add Wallet Amount" : "أضف مبلغ المحفظة",
      "Enter Amount" : "أدخل المبلغ",
      "Select Payment Method" : "حدد طريقة الدفع",
      "Enter Amount!!!" : "أدخل المبلغ!!!",
      "Top-up" : "إعادة الشحن",
      "Join Our App and Make a Difference:" : "انضم إلى تطبيقنا وأحدث فرقًا:",
      "Donate Today!" : "تبرع اليوم!",
      "Invite friend" : "ادعُ صديقًا",
      "Transaction History" : "سجل المعاملات",
      "Debit" : "الخصم",
      "Creadit" : "Creadit",
      "Welcome to Your ZippyGo Ride!" : "مرحبًا بك في رحلتك على ZippyGo!",
      "Your Journey, Just a Tap Away" : "رحلتك، بنقرة واحدة فقط",
      "Wherever You Go, We’re Here" : "أينما ذهبت، نحن هنا",
      "Book a ride in just a few taps and reach your destination comfortably" : "احجز رحلة ببضع نقرات فقط ووصل إلى وجهتك بشكل مريح",
      "Experience fast, reliable, and safe rides with ease." : "استمتع برحلات سريعة وموثوقة وآمنة بكل سهولة.",
      "Find a ride quickly and enjoy your journey hassle-free" : "اعثر على رحلة بسرعة واستمتع برحلتك دون أي متاعب",
      "Phone Number" : "رقم الهاتف",
      "By clicking Continue.you agree tp our " : "بالنقر فوق متابعة، فإنك توافق على",
      "T&Cs" : "شروط وأحكامنا",
      "Continue" : "متابعة",
      "Forget Password ?" : "نسيت كلمة المرور؟",
      "Enter Mobile Number...!!!" : "أدخل رقم الهاتف المحمول...!!!",
      "Forgot Password ?" : "نسيت كلمة المرور؟",
      "Milk made modern!" : "حليب عصري!",
      "Our app combines the convenience of technology with the tradition of the milkman" : "يجمع تطبيقنا بين راحة التكنولوجيا وتقاليد بائع الحليب",
      "Never miss a delivery again!" : "لا تفوت أي عملية توصيل مرة أخرى!",
      "With our app, you'll receive real-time notifications about your milk deliveries" : "من خلال تطبيقنا، ستتلقى إشعارات في الوقت الفعلي حول عمليات توصيل الحليب الخاصة بك",
      "Milk at your fingertips!" : "الحليب في متناول يدك!",
      "order fresh milk and dairy products for delivery straight to your doorstep" : "اطلب الحليب الطازج ومنتجات الألبان للتوصيل مباشرة إلى باب منزلك",
      "Get Started" : "ابدأ",
      "Step 1/3" : "الخطوة 1/3",
      "Let's get you trip-ready!" : "دعنا نجهزك للرحلة!",
      "Step 1/2" : "الخطوة 1/2",
      "Got an OTP?" : "هل لديك كلمة مرور لمرة واحدة؟",
      "Step 2/2" : "الخطوة 2/2",
      "Just one last thing" : "شيء أخير",
      "Full Name" : "الاسم الكامل",
      "email" : "البريد الإلكتروني",
      "Referral code(optional)" : "رمز الإحالة (اختياري)",
      "Referral code" : "رمز الإحالة",
      "Let's go!" : "لننطلق!",
      "No Chat Found!" : "لم يتم العثور على دردشة!",
      "Currently you don’t have chat." : "حاليًا ليس لديك دردشة.",
      "Say Something..." : "قل شيئًا...",
      "Reject" : "ارفض",
      "How much time do you need?" : "كم من الوقت تحتاج؟",
      "Leave now" : "اغادر الآن",
      "Leave later" : "اغادر لاحقًا",
      "Date and Time" : "التاريخ والوقت",
      "Starting at" : "يبدأ من",
      "Choose a ride" : "اختر رحلة",
    },
    'en_Hindi'     : {
      "Captains are busy" : "कैप्टन व्यस्त हैं",
      "Find a driver" : "ड्राइवर ढूँढ़ें",
      "City to city" : "शहर से शहर",
      "From" : "से",
      "To" : "से",
      "Departure date" : "तक",
      "Departure time" : "प्रस्थान तिथि",
      "Done" : "प्रस्थान समय",
      "Skip" : "हो गया",
      "Next" : "छोड़ें",
      "When" : "अगला",
      "Number of passengers" : "कब",
      "Set your price" : "यात्रियों की संख्या",
      "We charge no commission. Full" : "अपना मूल्य निर्धारित करें",
      "amount goes to the captain" : "हम कोई कमीशन नहीं लेते हैं। पूरी ",
      "Higher the price,higher the chance of" : "राशि कैप्टन को जाती है",
      "getting a ride" : "कीमत जितनी ज़्यादा होगी, सवारी मिलने की संभावना उतनी ही ज़्यादा होगी",
      "Automatically accept the nearest driver for your fare" : "अपने किराए के लिए निकटतम ड्राइवर को स्वचालित रूप से स्वीकार करें",
      "Offer your fare" : "अपना किराया ऑफ़र करें",
      "Comments" : "टिप्पणियाँ",
      "How many of you will go?" : "आप में से कितने लोग जाएँगे? ",
      "Captain on the way" : "कैप्टन रास्ते में है",
      "Captain has arrived" : "कैप्टन आ गया है",
      "Heading to the destination" : "गंतव्य की ओर बढ़ रहा है",
      "Start your order with PIN" : "पिन के साथ अपना ऑर्डर शुरू करें",
      "Pickup From" : "पिकअप से",
      "Trip Details" : "ट्रिप विवरण",
      "Rating" : "रेटिंग",
      "Trips" : "ट्रिप",
      "Joined" : "जॉइन किए गए",
      "Language" : "भाषा",
      "Preference" : "पसंद",
      "Choose a driver" : "ड्राइवर चुनें",
      "Driver can offer their fare and time" : "ड्राइवर अपना किराया और समय दे सकता है",
      "Decline" : "अस्वीकार करें",
      "Accept" : "स्वीकार करें",
      "Drop to" : "ड्रॉप करें",
      "Faq List" : "अक्सर पूछे जाने वाले प्रश्न सूची",
      "CONTINUE" : "जारी रखें",
      "Payment Getway Method" : "भुगतान गेटवे विधि",
      "All coupons" : "सभी कूपन",
      "Best Coupon" : "सर्वश्रेष्ठ कूपन",
      "Coupon Code: " : "कूपन कोड:",
      "Coupon Amount: " : "कूपन राशि:",
      "Minimum Amount: " : "न्यूनतम राशि:",
      "Ex Date: " : "पूर्व तिथि:",
      "Remove" : "हटाएँ",
      "Apply coupons" : "कूपन लागू करें",
      "Coupon" : "कूपन",
      "Coupon applied" : "कूपन लागू किया गया",
      "Try Again" : "पुनः प्रयास करें",
      "Cancel" : "रद्द करें",
      "Home" : "होम",
      "My Ride" : "मेरी सवारी",
      "Wallet" : "वॉलेट",
      "Profile" : "प्रोफ़ाइल",
      "Faq" : "अक्सर पूछे जाने वाले प्रश्न",
      "Refer and earn" : "रेफ़र करें और कमाएँ",
      "Notifications" : "सूचनाएँ",
      "Your Current Location" : "आपका वर्तमान स्थान",
      "Close" : "बंद करें",
      "Searching for you on the map..." : "मानचित्र पर आपको खोज रहा है...",
      "💡Raise the fare, increase your chances." : "💡किराया बढ़ाएँ, अपने अवसर बढ़ाएँ।",
      "Automatically book the nearest driver for" : "अपने आप निकटतम ड्राइवर बुक करें",
      "Cancel Request" : "अनुरोध रद्द करें",
      "cancel" : "रद्द करें",
      "Completed" : "पूर्ण",
      "Invoice" : "चालान",
      "Rate your ride" : "अपनी सवारी को रेट करें",
      "Pickup" : "पिकअप",
      "Destination" : "गंतव्य",
      "RIDE DETAIL" : "सवारी विवरण",
      "Ride Type :" : "सवारी का प्रकार:",
      "Car Type :" : "कार का प्रकार:",
      "hours / minit :" : "घंटे/मिनट:",
      "Date & Time :" : "दिनांक और समय:",
      "PAYMENT" : "भुगतान",
      "Ride Fair :" : "सवारी किराया:",
      "Promo :" : "प्रोमो:",
      "PlatformFee :" : "प्लेटफ़ॉर्म शुल्क:",
      "Weather Price :" : "मौसम मूल्य:",
      "Total :" : "कुल:",
      "My Rides" : "मेरी सवारी",
      "Upcoming" : "आगामी",
      "Cancelled" : "रद्द",
      "Notification" : "सूचना",
      "No new notifications" : "कोई नई सूचना नहीं",
      "Looks like you haven't received any notification" : "ऐसा लगता है कि आपको कोई सूचना नहीं मिली है",
      "Allow Notifications and on-ride alerts" : "सूचनाओं और सवारी के दौरान अलर्ट की अनुमति दें",
      "Real-time Captain updates" : "वास्तविक समय में कप्तान के अपडेट",
      "Get notified about captain`s allocation, arrival and more" : "कप्तान के आवंटन, आगमन और अधिक के बारे में सूचना प्राप्त करें",
      "Be the first to know about our offers and new features" : "हमारे ऑफ़र और नई सुविधाओं के बारे में सबसे पहले जानें",
      "Allow" : "अनुमति दें",
      "Maybe, later" : "शायद, बाद में",
      "Location permission not enabled" : "स्थान अनुमति सक्षम नहीं है",
      "Sharing Location permission helps us improve your ride booking and pickup experience" : "स्थान साझा करने की अनुमति हमें आपकी सवारी बुकिंग और पिकअप अनुभव को बेहतर बनाने में मदद करती है",
      "Allow Permission" : "अनुमति दें",
      "Enter pickup manually" : "मैन्युअल रूप से पिकअप दर्ज करें",
      "Drop" : "ड्रॉप करें",
      "Drop location" : "स्थान ड्रॉप करें",
      "Select on map" : "मानचित्र पर चुनें",
      "Add a destination" : "गंतव्य जोड़ें",
      "Update" : "अपडेट करें",
      "My Profile" : "मेरा प्रोफ़ाइल",
      "Name" : "नाम",
      "Email" : "ईमेल",
      "Password" : "पासवर्ड",
      "Refer your friends" : "अपने मित्रों को रेफ़र करें",
      "& Earn Coins!" : "और सिक्के कमाएँ!",
      "Invite all your friend to " : "अपने सभी मित्रों को आमंत्रित करें",
      "ZippyGo" : "ZippyGo",
      "Your referred person gets " : "आपके द्वारा रेफ़र किया गया व्यक्ति आपके कोड का उपयोग करके साइन अप करने पर",
      "coins when they sign up using your code" : "सिक्के प्राप्त करता है",
      "and you receive " : "और आपको",
      "coins when the person you referred purchases a membership." : "सिक्के तब प्राप्त होते हैं जब आपके द्वारा रेफ़र किया गया व्यक्ति सदस्यता खरीदता है।",
      "Start inviting friends today and enjoy the benefits together!" : "आज ही दोस्तों को आमंत्रित करना शुरू करें और साथ मिलकर लाभों का आनंद लें!",
      "Refer a Friend" : "किसी मित्र को रेफ़र करें",
      "Help" : "मदद करें",
      "H" : "H",
      "RIDE COMPLETED" : "राइड पूरी हुई",
      "Select a payment method to pay" : "भुगतान करने के लिए भुगतान विधि चुनें",
      "Total trip fare" : "कुल यात्रा किराया",
      "Ride Charges" : "सवारी शुल्क",
      "Discount" : "छूट",
      "Whether Charge" : "क्या शुल्क लिया जाएगा",
      "Platform fee" : "प्लेटफ़ॉर्म शुल्क",
      "AMOUNT TO BE PAID" : "भुगतान की जाने वाली राशि",
      "Payment Gateway Method" : "भुगतान गेटवे विधि",
      "Total Balance" : "कुल शेष राशि",
      "Add Wallet Amount" : "वॉलेट राशि जोड़ें",
      "Enter Amount" : "राशि दर्ज करें",
      "Select Payment Method" : "भुगतान विधि चुनें",
      "Enter Amount!!!" : "राशि दर्ज करें!!!",
      "Top-up" : "टॉप-अप",
      "Join Our App and Make a Difference:" : "हमारे ऐप से जुड़ें और बदलाव लाएँ:",
      "Donate Today!" : "आज ही दान करें!",
      "Invite friend" : "मित्र को आमंत्रित करें",
      "Transaction History" : "लेन-देन इतिहास",
      "Debit" : "डेबिट",
      "Creadit" : "क्रेडिट",
      "Welcome to Your ZippyGo Ride!" : "आपका ZippyGo राइड में स्वागत है!",
      "Your Journey, Just a Tap Away" : "आपकी यात्रा, बस एक टैप दूर",
      "Wherever You Go, We’re Here" : "आप जहाँ भी जाएँ, हम यहाँ हैं",
      "Book a ride in just a few taps and reach your destination comfortably" : "बस कुछ ही टैप में राइड बुक करें और आराम से अपने गंतव्य तक पहुँचें",
      "Experience fast, reliable, and safe rides with ease." : "आसानी से तेज़, विश्वसनीय और सुरक्षित राइड का अनुभव करें।",
      "Find a ride quickly and enjoy your journey hassle-free" : "जल्दी से राइड ढूँढ़ें और बिना किसी परेशानी के अपनी यात्रा का आनंद लें",
      "Phone Number" : "फ़ोन नंबर",
      "By clicking Continue.you agree tp our " : "जारी रखें पर क्लिक करके, आप हमारी शर्तों और नियमों से सहमत होते हैं",
      "T&Cs" : "T&Cs",
      "Continue" : "जारी रखें",
      "Forget Password ?" : "पासवर्ड भूल गए?",
      "Enter Mobile Number...!!!" : "मोबाइल नंबर दर्ज करें...!!!",
      "Forgot Password ?" : "पासवर्ड भूल गए?",
      "Milk made modern!" : "दूध आधुनिक बना दिया!",
      "Our app combines the convenience of technology with the tradition of the milkman" : "हमारा ऐप दूधवाले की परंपरा के साथ तकनीक की सुविधा को जोड़ता है",
      "Never miss a delivery again!" : "अब कभी भी डिलीवरी मिस न करें!",
      "With our app, you'll receive real-time notifications about your milk deliveries" : "हमारे ऐप के साथ, आपको अपने दूध की डिलीवरी के बारे में वास्तविक समय की सूचनाएँ प्राप्त होंगी",
      "Milk at your fingertips!" : "दूध आपकी उंगलियों पर!",
      "order fresh milk and dairy products for delivery straight to your doorstep" : "ताज़ा दूध और डेयरी उत्पादों को सीधे आपके दरवाजे पर डिलीवरी के लिए ऑर्डर करें",
      "Get Started" : "शुरू करें",
      "Step 1/3" : "चरण 1/3",
      "Let's get you trip-ready!" : "चलिए आपको यात्रा के लिए तैयार करते हैं!",
      "Step 1/2" : "चरण 1/2",
      "Got an OTP?" : "क्या आपको OTP मिला है?",
      "Step 2/2" : "चरण 2/2",
      "Just one last thing" : "बस एक आखिरी बात",
      "Full Name" : "पूरा नाम",
      "email" : "ईमेल",
      "Referral code(optional)" : "रेफ़रल कोड (वैकल्पिक)",
      "Referral code" : "रेफ़रल कोड",
      "Let's go!" : "चलो चलें!",
      "No Chat Found!" : "कोई चैट नहीं मिली!",
      "Currently you don’t have chat." : "वर्तमान में आपके पास चैट नहीं है।",
      "Say Something..." : "कुछ कहो...",
      "Reject" : "अस्वीकार करें",
      "How much time do you need?" : "आपको कितना समय चाहिए?",
      "Leave now" : "अभी निकलें",
      "Leave later" : "बाद में निकलें",
      "Date and Time" : "तारीख और समय",
      "Starting at" : "शुरू होने वाला",
      "Choose a ride" : "एक सवारी चुनें",
    },
    'en_Gujarati'  : {
      "Captains are busy" : "કેપ્ટન વ્યસ્ત છે",
      "Find a driver" : "ડ્રાઇવર શોધો",
      "City to city" : "શહેરથી શહેર",
      "From" : "થી",
      "To" : "થી",
      "Departure date" : "પ્રસ્થાન તારીખ",
      "Departure time" : "પ્રસ્થાન સમય",
      "Done" : "થઈ ગયું",
      "Skip" : "છોડો",
      "Next" : "આગળ",
      "When" : "જ્યારે",
      "Number of passengers" : "મુસાફરોની સંખ્યા",
      "Set your price" : "તમારી કિંમત સેટ કરો",
      "We charge no commission. Full" : "અમે કોઈ કમિશન લેતા નથી. સંપૂર્ણ",
      "amount goes to the captain" : "રકમ કેપ્ટનને જાય છે",
      "Higher the price,higher the chance of" : "ઊંચી કિંમત, ઉચ્ચ તક",
      "getting a ride" : "સવારી મેળવવી",
      "Automatically accept the nearest driver for your fare" : "તમારા ભાડા માટે નજીકના ડ્રાઇવરને આપમેળે સ્વીકારો",
      "Offer your fare" : "તમારું ભાડું ઑફર કરો",
      "Comments" : "ટિપ્પણીઓ",
      "How many of you will go?" : "તમારામાંથી કેટલા જશે?",
      "Captain on the way" : "રસ્તામાં કેપ્ટન",
      "Captain has arrived" : "કેપ્ટન આવી ગયો",
      "Heading to the destination" : "લક્ષ્યસ્થાન તરફ જઈ રહ્યા છીએ",
      "Start your order with PIN" : "તમારો ઓર્ડર પિન વડે શરૂ કરો",
      "Pickup From" : "થી પિકઅપ",
      "Trip Details" : "પ્રવાસની વિગતો",
      "Rating" : "રેટિંગ",
      "Trips" : "પ્રવાસો",
      "Joined" : "જોડાયા",
      "Language" : "ભાષા",
      "Preference" : "પસંદગી",
      "Choose a driver" : "ડ્રાઇવર પસંદ કરો",
      "Driver can offer their fare and time" : "ડ્રાઈવર તેમનું ભાડું અને સમય ઓફર કરી શકે છે",
      "Decline" : "નકાર",
      "Accept" : "સ્વીકારો",
      "Drop to" : "પર છોડો",
      "Faq List" : "FAQ સૂચિ",
      "CONTINUE" : "ચાલુ રાખો",
      "Payment Getway Method" : "ચુકવણી ગેટવે પદ્ધતિ",
      "All coupons" : "બધા કૂપન્સ",
      "Best Coupon" : "શ્રેષ્ઠ કૂપન",
      "Coupon Code: " : "કૂપન કોડ:",
      "Coupon Amount: " : "કૂપનની રકમ:",
      "Minimum Amount: " : "ન્યૂનતમ રકમ:",
      "Ex Date: " : "ભૂતપૂર્વ તારીખ:",
      "Remove" : "દૂર કરો",
      "Apply coupons" : "કૂપન્સ લાગુ કરો",
      "Coupon" : "કૂપન",
      "Coupon applied" : "કૂપન લાગુ કરી",
      "Try Again" : "ફરી પ્રયાસ કરો",
      "Cancel" : "રદ કરો",
      "Home" : "ઘર",
      "My Ride" : "મારી રાઈડ",
      "Wallet" : "વૉલેટ",
      "Profile" : "પ્રોફાઇલ",
      "Faq" : "FAQ",
      "Refer and earn" : "સંદર્ભ લો અને કમાઓ",
      "Notifications" : "સૂચનાઓ",
      "Your Current Location" : "તમારું વર્તમાન સ્થાન",
      "Close" : "બંધ કરો",
      "Searching for you on the map..." : "નકશા પર તમને શોધી રહ્યાં છીએ...",
      "💡Raise the fare, increase your chances." : "💡ભાડું વધારો, તમારી તકો વધારો.",
      "Automatically book the nearest driver for" : "માટે નજીકના ડ્રાઇવરને આપમેળે બુક કરો",
      "Cancel Request" : "વિનંતી રદ કરો",
      "cancel" : "રદ કરો",
      "Completed" : "પૂર્ણ થયું",
      "Invoice" : "ભરતિયું",
      "Rate your ride" : "તમારી સવારીને રેટ કરો",
      "Pickup" : "પિકઅપ",
      "Destination" : "ગંતવ્ય",
      "RIDE DETAIL" : "રાઇડ ડિટેલ",
      "Ride Type :" : "સવારીનો પ્રકાર:",
      "Car Type :" : "કારનો પ્રકાર:",
      "hours / minit :" : "કલાક/મિનિટ:",
      "Date & Time :" : "તારીખ અને સમય:",
      "PAYMENT" : "ચુકવણી",
      "Ride Fair :" : "રાઇડ ફેર:",
      "Promo :" : "પ્રોમો:",
      "PlatformFee :" : "પ્લેટફોર્મ ફી:",
      "Weather Price :" : "હવામાન કિંમત:",
      "Total :" : "કુલ:",
      "My Rides" : "મારી સવારી",
      "Upcoming" : "આગામી",
      "Cancelled" : "રદ કરેલ",
      "Notification" : "સૂચના",
      "No new notifications" : "કોઈ નવી સૂચનાઓ નથી",
      "Looks like you haven't received any notification" : "એવું લાગે છે કે તમને કોઈ સૂચના મળી નથી",
      "Allow Notifications and on-ride alerts" : "સૂચનાઓ અને સવારી પર ચેતવણીઓને મંજૂરી આપો",
      "Real-time Captain updates" : "રીઅલ-ટાઇમ કેપ્ટન અપડેટ્સ",
      "Get notified about captain`s allocation, arrival and more" : "કેપ્ટનની ફાળવણી, આગમન અને વધુ વિશે સૂચના મેળવો",
      "Be the first to know about our offers and new features" : "અમારી ઑફરો અને નવી સુવિધાઓ વિશે જાણનારા પ્રથમ બનો",
      "Allow" : "પરવાનગી આપે છે",
      "Maybe, later" : "કદાચ, પછીથી",
      "Location permission not enabled" : "સ્થાન પરવાનગી સક્ષમ નથી",
      "Sharing Location permission helps us improve your ride booking and pickup experience" : "શેરિંગ સ્થાન પરવાનગી અમને તમારા રાઈડ બુકિંગ અને પિકઅપ અનુભવને બહેતર બનાવવામાં મદદ કરે છે",
      "Allow Permission" : "પરવાનગી આપો",
      "Enter pickup manually" : "મેન્યુઅલી પિકઅપ દાખલ કરો",
      "Drop" : "છોડો",
      "Drop location" : "સ્થાન છોડો",
      "Select on map" : "નકશા પર પસંદ કરો",
      "Add a destination" : "એક ગંતવ્ય ઉમેરો",
      "Update" : "અપડેટ કરો",
      "My Profile" : "મારી પ્રોફાઇલ",
      "Name" : "નામ",
      "Email" : "ઈમેલ",
      "Password" : "પાસવર્ડ",
      "Refer your friends" : "તમારા મિત્રો નો સંદર્ભ લો",
      "& Earn Coins!" : "અને સિક્કા કમાઓ!",
      "Invite all your friend to " : "તમારા બધા મિત્રોને આમંત્રણ આપો",
      "ZippyGo" : "ZippyGo",
      "Your referred person gets " : "તમારા સંદર્ભિત વ્યક્તિને મળે છે",
      "coins when they sign up using your code" : " જ્યારે તેઓ તમારા કોડનો ઉપયોગ કરીને સાઇન અપ કરે છે",
      "and you receive " : "અને તમે પ્રાપ્ત કરો છો",
      "coins when the person you referred purchases a membership." : " જ્યારે તમે ઉલ્લેખિત વ્યક્તિ સભ્યપદ ખરીદે ત્યારે સિક્કા.",
      "Start inviting friends today and enjoy the benefits together!" : "આજે જ મિત્રોને આમંત્રિત કરવાનું શરૂ કરો અને સાથે મળીને લાભોનો આનંદ માણો!",
      "Refer a Friend" : "મિત્રનો સંદર્ભ લો",
      "Help" : "મદદ",
      "H" : "એચ",
      "RIDE COMPLETED" : "રાઇડ પૂર્ણ",
      "Select a payment method to pay" : "ચૂકવણી કરવા માટે ચુકવણી પદ્ધતિ પસંદ કરો",
      "Total trip fare" : "કુલ પ્રવાસ ભાડું",
      "Ride Charges" : "રાઇડ ચાર્જીસ",
      "Discount" : "ડિસ્કાઉન્ટ",
      "Whether Charge" : "શું ચાર્જ",
      "Platform fee" : "પ્લેટફોર્મ ફી",
      "AMOUNT TO BE PAID" : "ચૂકવવા માટેની રકમ",
      "Payment Gateway Method" : "ચુકવણી ગેટવે પદ્ધતિ",
      "Total Balance" : "કુલ બેલેન્સ",
      "Add Wallet Amount" : "વૉલેટની રકમ ઉમેરો",
      "Enter Amount" : "રકમ દાખલ કરો",
      "Select Payment Method" : "ચુકવણી પદ્ધતિ પસંદ કરો",
      "Enter Amount!!!" : "રકમ દાખલ કરો !!!",
      "Top-up" : "ટોપ-અપ",
      "Join Our App and Make a Difference:" : "અમારી એપ્લિકેશનમાં જોડાઓ અને તફાવત બનાવો:",
      "Donate Today!" : "આજે દાન કરો!",
      "Invite friend" : "મિત્રને આમંત્રણ આપો",
      "Transaction History" : "વ્યવહાર ઇતિહાસ",
      "Debit" : "ડેબિટ",
      "Creadit" : "ક્રેડિટ",
      "Welcome to Your ZippyGo Ride!" : "તમારી ZippyGo રાઈડમાં આપનું સ્વાગત છે!",
      "Your Journey, Just a Tap Away" : "તમારી મુસાફરી, માત્ર એક ટેપ દૂર",
      "Wherever You Go, We’re Here" : "તમે જ્યાં પણ જાઓ, અમે અહીં છીએ",
      "Book a ride in just a few taps and reach your destination comfortably" : "થોડી જ વારમાં રાઈડ બુક કરો અને તમારા ગંતવ્ય પર આરામથી પહોંચો",
      "Experience fast, reliable, and safe rides with ease." : "સરળતા સાથે ઝડપી, ભરોસાપાત્ર અને સલામત રાઈડનો અનુભવ કરો.",
      "Find a ride quickly and enjoy your journey hassle-free" : "ઝડપથી રાઈડ શોધો અને તમારી મુશ્કેલી વિનાની મુસાફરીનો આનંદ માણો",
      "Phone Number" : "ફોન નંબર",
      "By clicking Continue.you agree tp our " : "Continue.You પર ક્લિક કરીને તમે અમારી સાથે સંમત થાઓ છો",
      "T&Cs" : "T&Cs",
      "Continue" : "ચાલુ રાખો",
      "Forget Password ?" : "પાસવર્ડ ભૂલી જાઓ છો?",
      "Enter Mobile Number...!!!" : "મોબાઈલ નંબર દાખલ કરો...!!!",
      "Forgot Password ?" : "પાસવર્ડ ભૂલી ગયા છો?",
      "Milk made modern!" : "દૂધ આધુનિક બનાવ્યું!",
      "Our app combines the convenience of technology with the tradition of the milkman" : "અમારી એપ્લિકેશન ટેક્નોલોજીની સુવિધાને દૂધવાળાની પરંપરા સાથે જોડે છે",
      "Never miss a delivery again!" : "ફરી ક્યારેય ડિલિવરી ચૂકશો નહીં!",
      "With our app, you'll receive real-time notifications about your milk deliveries" : "અમારી એપ્લિકેશન સાથે, તમને તમારા દૂધની ડિલિવરી વિશે રીઅલ-ટાઇમ સૂચનાઓ પ્રાપ્ત થશે",
      "Milk at your fingertips!" : "તમારી આંગળીના વેઢે દૂધ!",
      "order fresh milk and dairy products for delivery straight to your doorstep" : "સીધા તમારા ઘરના ઘરે પહોંચાડવા માટે તાજા દૂધ અને ડેરી ઉત્પાદનોનો ઓર્ડર આપો",
      "Get Started" : "પ્રારંભ કરો",
      "Step 1/3" : "પગલું 1/3",
      "Let's get you trip-ready!" : "ચાલો તમને ટ્રિપ માટે તૈયાર કરીએ!",
      "Step 1/2" : "પગલું 1/2",
      "Got an OTP?" : "OTP મળ્યો?",
      "Step 2/2" : "પગલું 2/2",
      "Just one last thing" : "બસ એક છેલ્લી વાત",
      "Full Name" : "પૂરું નામ",
      "email" : "ઇમેઇલ",
      "Referral code(optional)" : "રેફરલ કોડ (વૈકલ્પિક)",
      "Referral code" : "રેફરલ કોડ",
      "Let's go!" : "ચાલો જઈએ!",
      "No Chat Found!" : "કોઈ ચેટ મળી નથી!",
      "Currently you don’t have chat." : "હાલમાં તમારી પાસે ચેટ નથી.",
      "Say Something..." : "કંઈક બોલો...",
      "Reject" : "અસ્વીકાર કરો",
      "How much time do you need?" : "તમારે કેટલો સમય જોઈએ છે?",
      "Leave now" : "હવે છોડો",
      "Leave later" : "પછી છોડી દો",
      "Date and Time" : "તારીખ અને સમય",
      "Starting at" : "થી શરૂ થાય છે",
      "Choose a ride" : "સવારી પસંદ કરો",
    },
    'en_African'   : {
      "Captains are busy" : "Kapteins is besig",
      "Find a driver" : "Soek 'n bestuurder",
      "City to city" : "Stad tot stad",
      "From" : "Van",
      "To" : "Om",
      "Departure date" : "Vertrekdatum",
      "Departure time" : "Vertrek tyd",
      "Done" : "Klaar",
      "Skip" : "Slaan oor",
      "Next" : "Volgende",
      "When" : "Wanneer",
      "Number of passengers" : "Aantal passasiers",
      "Set your price" : "Stel jou prys",
      "We charge no commission. Full" : "Ons hef geen kommissie nie. Vol",
      "amount goes to the captain" : "bedrag gaan aan die kaptein",
      "Higher the price,higher the chance of" : "Hoër die prys, groter die kans om",
      "getting a ride" : "ry kry",
      "Automatically accept the nearest driver for your fare" : "Aanvaar outomaties die naaste bestuurder vir jou tarief",
      "Offer your fare" : "Bied jou tarief aan",
      "Comments" : "Kommentaar",
      "How many of you will go?" : "Hoeveel van julle sal gaan?",
      "Captain on the way" : "Kaptein op pad",
      "Captain has arrived" : "Kaptein het aangekom",
      "Heading to the destination" : "Op pad na die bestemming",
      "Start your order with PIN" : "Begin jou bestelling met PIN",
      "Pickup From" : "Afhaal vanaf",
      "Trip Details" : "Reisbesonderhede",
      "Rating" : "Gradering",
      "Trips" : "Reise",
      "Joined" : "Aangesluit",
      "Language" : "Taal",
      "Preference" : "Voorkeur",
      "Choose a driver" : "Kies 'n bestuurder",
      "Driver can offer their fare and time" : "Bestuurder kan hul tarief en tyd aanbied",
      "Decline" : "Weier",
      "Accept" : "Aanvaar",
      "Drop to" : "Val na",
      "Faq List" : "Faq Lys",
      "CONTINUE" : "VERDER",
      "Payment Getway Method" : "Betaling Getway Metode",
      "All coupons" : "Alle koepons",
      "Best Coupon" : "Beste koepon",
      "Coupon Code: " : "Koeponkode:",
      "Coupon Amount: " : "Koeponbedrag:",
      "Minimum Amount: " : "Minimum bedrag:",
      "Ex Date: " : "Bv datum:",
      "Remove" : "Verwyder",
      "Apply coupons" : "Pas koepons toe",
      "Coupon" : "Koepon",
      "Coupon applied" : "Koepon toegepas",
      "Try Again" : "Probeer weer",
      "Cancel" : "Kanselleer",
      "Home" : "Tuis",
      "My Ride" : "My Rit",
      "Wallet" : "Beursie",
      "Profile" : "Profiel",
      "Faq" : "Gereelde vrae",
      "Refer and earn" : "Verwys en verdien",
      "Notifications" : "Kennisgewings",
      "Your Current Location" : "Jou huidige ligging",
      "Close" : "Maak toe",
      "Searching for you on the map..." : "Soek tans vir jou op die kaart...",
      "💡Raise the fare, increase your chances." : "💡Verhoog die tarief, verhoog jou kanse.",
      "Automatically book the nearest driver for" : "Bespreek outomaties die naaste bestuurder vir",
      "Cancel Request" : "Kanselleer versoek",
      "cancel" : "kanselleer",
      "Completed" : "Voltooi",
      "Invoice" : "Faktuur",
      "Rate your ride" : "Beoordeel jou rit",
      "Pickup" : "Bakkie",
      "Destination" : "Bestemming",
      "RIDE DETAIL" : "RIT DETAIL",
      "Ride Type :" : "Rit tipe:",
      "Car Type :" : "Kar Tipe:",
      "hours / minit :" : "ure / minit:",
      "Date & Time :" : "Datum & Tyd:",
      "PAYMENT" : "BETALING",
      "Ride Fair :" : "Ride Fair:",
      "Promo :" : "Promosie:",
      "PlatformFee :" : "Platformfooi:",
      "Weather Price :" : "Weer Prys:",
      "Total :" : "Totaal:",
      "My Rides" : "My ritte",
      "Upcoming" : "Komende",
      "Cancelled" : "Gekanselleer",
      "Notification" : "Kennisgewing",
      "No new notifications" : "Geen nuwe kennisgewings nie",
      "Looks like you haven't received any notification" : "Dit lyk of jy geen kennisgewing ontvang het nie",
      "Allow Notifications and on-ride alerts" : "Laat kennisgewings en op-rit-waarskuwings toe",
      "Real-time Captain updates" : "Intydse Kaptein-opdaterings",
      "Get notified about captain`s allocation, arrival and more" : "Word in kennis gestel oor kaptein se toekenning, aankoms en meer",
      "Be the first to know about our offers and new features" : "Wees die eerste om te weet van ons aanbiedinge en nuwe kenmerke",
      "Allow" : "Laat toe",
      "Maybe, later" : "Miskien, later",
      "Location permission not enabled" : "Liggingtoestemming nie geaktiveer nie",
      "Sharing Location permission helps us improve your ride booking and pickup experience" : "Om liggingtoestemming te deel, help ons om jou ritbespreking en afhaalervaring te verbeter",
      "Allow Permission" : "Laat toestemming toe",
      "Enter pickup manually" : "Voer bakkie handmatig in",
      "Drop" : "Laat val",
      "Drop location" : "Los ligging",
      "Select on map" : "Kies op kaart",
      "Add a destination" : "Voeg 'n bestemming by",
      "Update" : "Dateer op",
      "My Profile" : "My profiel",
      "Name" : "Naam",
      "Email" : "E-pos",
      "Password" : "Wagwoord",
      "Refer your friends" : "Verwys jou vriende",
      "& Earn Coins!" : "& Verdien Munte!",
      "Invite all your friend to " : "Nooi al jou vriende na",
      "ZippyGo" : "ZippyGo",
      "Your referred person gets " : "Jou verwysde persoon kry",
      "coins when they sign up using your code" : " munte wanneer hulle inteken met jou kode",
      "and you receive " : "en jy ontvang",
      "coins when the person you referred purchases a membership." : " munte wanneer die persoon wat jy verwys het, 'n lidmaatskap koop.",
      "Start inviting friends today and enjoy the benefits together!" : "Begin vandag vriende nooi en geniet die voordele saam!",
      "Refer a Friend" : "Verwys 'n Vriend",
      "Help" : "Help",
      "H" : "H",
      "RIDE COMPLETED" : "RIT VOLTOOI",
      "Select a payment method to pay" : "Kies 'n betaalmetode om te betaal",
      "Total trip fare" : "Totale reistarief",
      "Ride Charges" : "Ritheffings",
      "Discount" : "Afslag",
      "Whether Charge" : "Of Charge",
      "Platform fee" : "Platform fooi",
      "AMOUNT TO BE PAID" : "BEDRAG MOET BETAAL WORD",
      "Payment Gateway Method" : "Betalingspoortmetode",
      "Total Balance" : "Totale balans",
      "Add Wallet Amount" : "Voeg beursiebedrag by",
      "Enter Amount" : "Voer bedrag in",
      "Select Payment Method" : "Kies Betaalmetode",
      "Enter Amount!!!" : "Voer bedrag in!!!",
      "Top-up" : "Aanvulling",
      "Join Our App and Make a Difference:" : "Sluit aan by ons toepassing en maak 'n verskil:",
      "Donate Today!" : "Skenk vandag!",
      "Invite friend" : "Nooi vriend",
      "Transaction History" : "Transaksiegeskiedenis",
      "Debit" : "Debiet",
      "Creadit" : "Krediet",
      "Welcome to Your ZippyGo Ride!" : "Welkom by jou ZippyGo-rit!",
      "Your Journey, Just a Tap Away" : "Jou reis, net 'n tik weg",
      "Wherever You Go, We’re Here" : "Waar jy ook al gaan, ons is hier",
      "Book a ride in just a few taps and reach your destination comfortably" : "Bespreek 'n rit in net 'n paar krane en bereik jou bestemming gemaklik",
      "Experience fast, reliable, and safe rides with ease." : "Ervaar vinnige, betroubare en veilige ritte met gemak.",
      "Find a ride quickly and enjoy your journey hassle-free" : "Vind vinnig 'n rit en geniet jou reis moeitevry",
      "Phone Number" : "Telefoonnommer",
      "By clicking Continue.you agree tp our " : "Deur op Continue te klik, stem jy in met ons",
      "T&Cs" : "T&V's",
      "Continue" : "Gaan voort",
      "Forget Password ?" : "Wagwoord vergeet?",
      "Enter Mobile Number...!!!" : "Voer selfoonnommer in...!!!",
      "Forgot Password ?" : "Wagwoord vergeet?",
      "Milk made modern!" : "Melk modern gemaak!",
      "Our app combines the convenience of technology with the tradition of the milkman" : "Ons app kombineer die gerief van tegnologie met die tradisie van die melkman",
      "Never miss a delivery again!" : "Moet nooit weer 'n aflewering mis nie!",
      "With our app, you'll receive real-time notifications about your milk deliveries" : "Met ons toepassing sal jy intydse kennisgewings oor jou melkaflewerings ontvang",
      "Milk at your fingertips!" : "Melk op jou vingers!",
      "order fresh milk and dairy products for delivery straight to your doorstep" : "bestel vars melk en suiwelprodukte vir aflewering reguit by jou voorstoep",
      "Get Started" : "Begin",
      "Step 1/3" : "Stap 1/3",
      "Let's get you trip-ready!" : "Kom ons maak jou reisgereed!",
      "Step 1/2" : "Stap 1/2",
      "Got an OTP?" : "Het jy 'n OTP?",
      "Step 2/2" : "Stap 2/2",
      "Just one last thing" : "Net een laaste ding",
      "Full Name" : "Volle Naam",
      "email" : "e-pos",
      "Referral code(optional)" : "Verwysingskode (opsioneel)",
      "Referral code" : "Verwysingskode",
      "Let's go!" : "Kom ons gaan!",
      "No Chat Found!" : "Geen klets gevind nie!",
      "Currently you don’t have chat." : "Tans het jy nie klets nie.",
      "Say Something..." : "Sê iets...",
      "Reject" : "Verwerp",
      "How much time do you need?" : "Hoeveel tyd het jy nodig?",
      "Leave now" : "Los nou",
      "Leave later" : "Vertrek later",
      "Date and Time" : "Datum en Tyd",
      "Starting at" : "Begin by",
      "Choose a ride" : "Kies 'n rit",
    },
    'en_Bangali'   : {
      "Captains are busy" : "অধিনায়করা ব্যস্ত",
      "Find a driver" : "একজন ড্রাইভার খুঁজুন",
      "City to city" : "শহর থেকে শহরে",
      "From" : "থেকে",
      "To" : "প্রতি",
      "Departure date" : "প্রস্থান তারিখ",
      "Departure time" : "প্রস্থানের সময়",
      "Done" : "সম্পন্ন",
      "Skip" : "এড়িয়ে যান",
      "Next" : "পরবর্তী",
      "When" : "কখন",
      "Number of passengers" : "যাত্রীর সংখ্যা",
      "Set your price" : "আপনার মূল্য নির্ধারণ করুন",
      "We charge no commission. Full" : "আমরা কোন কমিশন চার্জ করি না। পূর্ণ",
      "amount goes to the captain" : "পরিমাণ ক্যাপ্টেনের কাছে যায়",
      "Higher the price,higher the chance of" : "দাম বেশি, সম্ভাবনাও বেশি",
      "getting a ride" : "একটি যাত্রা করা হচ্ছে",
      "Automatically accept the nearest driver for your fare" : "আপনার ভাড়ার জন্য নিকটতম ড্রাইভারকে স্বয়ংক্রিয়ভাবে গ্রহণ করুন",
      "Offer your fare" : "আপনার ভাড়া অফার",
      "Comments" : "মন্তব্য",
      "How many of you will go?" : "আপনারা কয়জন যাবেন?",
      "Captain on the way" : "পথে ক্যাপ্টেন",
      "Captain has arrived" : "ক্যাপ্টেন এসেছে",
      "Heading to the destination" : "গন্তব্যের দিকে যাচ্ছে",
      "Start your order with PIN" : "পিন দিয়ে আপনার অর্ডার শুরু করুন",
      "Pickup From" : "থেকে পিকআপ",
      "Trip Details" : "ভ্রমণের বিবরণ",
      "Rating" : "রেটিং",
      "Trips" : "ট্রিপ",
      "Joined" : "যোগদান করেছেন",
      "Language" : "ভাষা",
      "Preference" : "পছন্দ",
      "Choose a driver" : "একজন ড্রাইভার বেছে নিন",
      "Driver can offer their fare and time" : "ড্রাইভার তাদের ভাড়া এবং সময় দিতে পারেন",
      "Decline" : "প্রত্যাখ্যান",
      "Accept" : "গ্রহণ করুন",
      "Drop to" : "ড্রপ করুন",
      "Faq List" : "FAQ তালিকা",
      "CONTINUE" : "চালিয়ে যান",
      "Payment Getway Method" : "পেমেন্ট গেটওয়ে পদ্ধতি",
      "All coupons" : "সব কুপন",
      "Best Coupon" : "সেরা কুপন",
      "Coupon Code: " : "কুপন কোড:",
      "Coupon Amount: " : "কুপন পরিমাণ:",
      "Minimum Amount: " : "ন্যূনতম পরিমাণ:",
      "Ex Date: " : "প্রাক্তন তারিখ:",
      "Remove" : "সরান",
      "Apply coupons" : "কুপন প্রয়োগ করুন",
      "Coupon" : "কুপন",
      "Coupon applied" : "কুপন প্রয়োগ করা হয়েছে",
      "Try Again" : "আবার চেষ্টা করুন",
      "Cancel" : "বাতিল করুন",
      "Home" : "বাড়ি",
      "My Ride" : "আমার রাইড",
      "Wallet" : "ওয়ালেট",
      "Profile" : "প্রোফাইল",
      "Faq" : "প্রশ্ন",
      "Refer and earn" : "রেফার করে আয় করুন",
      "Notifications" : "বিজ্ঞপ্তি",
      "Your Current Location" : "আপনার বর্তমান অবস্থান",
      "Close" : "বন্ধ",
      "Searching for you on the map..." : "মানচিত্রে আপনাকে খুঁজছি...",
      "💡Raise the fare, increase your chances." : "💡ভাড়া বাড়ান, আপনার সুযোগ বাড়ান।",
      "Automatically book the nearest driver for" : "নিকটতম ড্রাইভারের জন্য স্বয়ংক্রিয়ভাবে বুক করুন",
      "Cancel Request" : "অনুরোধ বাতিল করুন",
      "cancel" : "বাতিল",
      "Completed" : "সম্পন্ন",
      "Invoice" : "চালান",
      "Rate your ride" : "আপনার রাইড রেট",
      "Pickup" : "পিকআপ",
      "Destination" : "গন্তব্য",
      "RIDE DETAIL" : "রাইড বিস্তারিত",
      "Ride Type :" : "রাইডের ধরন:",
      "Car Type :" : "গাড়ির ধরন:",
      "hours / minit :" : "ঘন্টা / মিনিট:",
      "Date & Time :" : "তারিখ ও সময়:",
      "PAYMENT" : "পেমেন্ট",
      "Ride Fair :" : "রাইড ফেয়ার:",
      "Promo :" : "প্রচার:",
      "PlatformFee :" : "প্ল্যাটফর্ম ফি:",
      "Weather Price :" : "আবহাওয়া মূল্য:",
      "Total :" : "মোট:",
      "My Rides" : "আমার রাইডস",
      "Upcoming" : "আসন্ন",
      "Cancelled" : "বাতিল",
      "Notification" : "বিজ্ঞপ্তি",
      "No new notifications" : "কোন নতুন বিজ্ঞপ্তি নেই",
      "Looks like you haven't received any notification" : "মনে হচ্ছে আপনি কোনো বিজ্ঞপ্তি পাননি",
      "Allow Notifications and on-ride alerts" : "বিজ্ঞপ্তি এবং অন-রাইড সতর্কতার অনুমতি দিন",
      "Real-time Captain updates" : "রিয়েল-টাইম ক্যাপ্টেন আপডেট",
      "Get notified about captain`s allocation, arrival and more" : "ক্যাপ্টেনের বরাদ্দ, আগমন এবং আরও অনেক কিছু সম্পর্কে বিজ্ঞপ্তি পান",
      "Be the first to know about our offers and new features" : "আমাদের অফার এবং নতুন বৈশিষ্ট্য সম্পর্কে প্রথম জানতে হবে",
      "Allow" : "অনুমতি দিন",
      "Maybe, later" : "হয়তো, পরে",
      "Location permission not enabled" : "অবস্থানের অনুমতি সক্ষম করা নেই",
      "Sharing Location permission helps us improve your ride booking and pickup experience" : "অবস্থানের অনুমতি শেয়ার করা আমাদের আপনার রাইড বুকিং এবং পিকআপ অভিজ্ঞতা উন্নত করতে সাহায্য করে",
      "Allow Permission" : "অনুমতি দিন",
      "Enter pickup manually" : "ম্যানুয়ালি পিকআপে প্রবেশ করুন",
      "Drop" : "ড্রপ",
      "Drop location" : "ড্রপ অবস্থান",
      "Select on map" : "মানচিত্রে নির্বাচন করুন",
      "Add a destination" : "একটি গন্তব্য যোগ করুন",
      "Update" : "আপডেট",
      "My Profile" : "আমার প্রোফাইল",
      "Name" : "নাম",
      "Email" : "ইমেইল",
      "Password" : "পাসওয়ার্ড",
      "Refer your friends" : "আপনার বন্ধুদের রেফার করুন",
      "& Earn Coins!" : "এবং কয়েন উপার্জন করুন!",
      "Invite all your friend to " : "আপনার সমস্ত বন্ধুকে আমন্ত্রণ জানান",
      "ZippyGo" : "জিপিগো",
      "Your referred person gets " : "আপনার উল্লেখিত ব্যক্তি পায়",
      "coins when they sign up using your code" : " কয়েন যখন তারা আপনার কোড ব্যবহার করে সাইন আপ করে",
      "and you receive " : "এবং আপনি গ্রহণ করেন",
      "coins when the person you referred purchases a membership." : " কয়েন যখন আপনি উল্লেখিত ব্যক্তি একটি সদস্যপদ ক্রয়.",
      "Start inviting friends today and enjoy the benefits together!" : "আজই বন্ধুদের আমন্ত্রণ জানানো শুরু করুন এবং একসাথে সুবিধাগুলি উপভোগ করুন!",
      "Refer a Friend" : "একটি বন্ধু উল্লেখ করুন",
      "Help" : "সাহায্য",
      "H" : "এইচ",
      "RIDE COMPLETED" : "রাইড সম্পূর্ণ হয়েছে",
      "Select a payment method to pay" : "পেমেন্ট করার জন্য একটি পেমেন্ট পদ্ধতি নির্বাচন করুন",
      "Total trip fare" : "মোট ভ্রমণ ভাড়া",
      "Ride Charges" : "রাইড চার্জ",
      "Discount" : "ছাড়",
      "Whether Charge" : "চার্জ কিনা",
      "Platform fee" : "প্ল্যাটফর্ম ফি",
      "AMOUNT TO BE PAID" : "অর্থ প্রদান করতে হবে",
      "Payment Gateway Method" : "পেমেন্ট গেটওয়ে পদ্ধতি",
      "Total Balance" : "মোট ব্যালেন্স",
      "Add Wallet Amount" : "ওয়ালেট পরিমাণ যোগ করুন",
      "Enter Amount" : "পরিমাণ লিখুন",
      "Select Payment Method" : "পেমেন্ট পদ্ধতি নির্বাচন করুন",
      "Enter Amount!!!" : "পরিমাণ লিখুন!!!",
      "Top-up" : "টপ-আপ",
      "Join Our App and Make a Difference:" : "আমাদের অ্যাপে যোগ দিন এবং একটি পার্থক্য তৈরি করুন:",
      "Donate Today!" : "আজ দান করুন!",
      "Invite friend" : "বন্ধুকে আমন্ত্রণ জানান",
      "Transaction History" : "লেনদেনের ইতিহাস",
      "Debit" : "ডেবিট",
      "Creadit" : "ক্রেডিট",
      "Welcome to Your ZippyGo Ride!" : "আপনার ZippyGo রাইডে স্বাগতম!",
      "Your Journey, Just a Tap Away" : "আপনার যাত্রা, শুধু একটি ট্যাপ দূরে",
      "Wherever You Go, We’re Here" : "আপনি যেখানেই যান, আমরা এখানে আছি",
      "Book a ride in just a few taps and reach your destination comfortably" : "মাত্র কয়েকটি ট্যাপে একটি রাইড বুক করুন এবং আরামে আপনার গন্তব্যে পৌঁছান",
      "Experience fast, reliable, and safe rides with ease." : "সহজে দ্রুত, নির্ভরযোগ্য এবং নিরাপদ রাইডের অভিজ্ঞতা নিন।",
      "Find a ride quickly and enjoy your journey hassle-free" : "দ্রুত একটি রাইড খুঁজুন এবং ঝামেলামুক্ত আপনার যাত্রা উপভোগ করুন",
      "Phone Number" : "ফোন নম্বর",
      "By clicking Continue.you agree tp our " : "Continue.You-এ ক্লিক করার মাধ্যমে আপনি আমাদের টিপিতে সম্মত হন",
      "T&Cs" : "T&Cs",
      "Continue" : "চালিয়ে যান",
      "Forget Password ?" : "পাসওয়ার্ড ভুলে গেছেন?",
      "Enter Mobile Number...!!!" : "মোবাইল নম্বর লিখুন...!!!",
      "Forgot Password ?" : "পাসওয়ার্ড ভুলে গেছেন?",
      "Milk made modern!" : "দুধের তৈরি আধুনিক!",
      "Our app combines the convenience of technology with the tradition of the milkman" : "আমাদের অ্যাপটি দুধওয়ালার ঐতিহ্যের সাথে প্রযুক্তির সুবিধার সমন্বয় করে",
      "Never miss a delivery again!" : "আর কখনো ডেলিভারি মিস করবেন না!",
      "With our app, you'll receive real-time notifications about your milk deliveries" : "আমাদের অ্যাপের মাধ্যমে, আপনি আপনার দুধ বিতরণ সম্পর্কে রিয়েল-টাইম বিজ্ঞপ্তি পাবেন",
      "Milk at your fingertips!" : "আপনার নখদর্পণে দুধ!",
      "order fresh milk and dairy products for delivery straight to your doorstep" : "সরাসরি আপনার দোরগোড়ায় ডেলিভারির জন্য তাজা দুধ এবং দুগ্ধজাত পণ্য অর্ডার করুন",
      "Get Started" : "শুরু করুন",
      "Step 1/3" : "ধাপ 1/3",
      "Let's get you trip-ready!" : "আপনাকে ট্রিপ প্রস্তুত করা যাক!",
      "Step 1/2" : "ধাপ 1/2",
      "Got an OTP?" : "একটি OTP পেয়েছেন?",
      "Step 2/2" : "ধাপ 2/2",
      "Just one last thing" : "শুধু একটি শেষ জিনিস",
      "Full Name" : "পুরো নাম",
      "email" : "ইমেইল",
      "Referral code(optional)" : "রেফারেল কোড (ঐচ্ছিক)",
      "Referral code" : "রেফারেল কোড",
      "Let's go!" : "চলুন!",
      "No Chat Found!" : "কোন চ্যাট পাওয়া যায়নি!",
      "Currently you don’t have chat." : "বর্তমানে আপনার চ্যাট নেই।",
      "Say Something..." : "কিছু বলুন...",
      "Reject" : "প্রত্যাখ্যান করুন",
      "How much time do you need?" : "আপনি কত সময় প্রয়োজন?",
      "Leave now" : "এখন চলে যাও",
      "Leave later" : "পরে চলে যান",
      "Date and Time" : "তারিখ এবং সময়",
      "Starting at" : "এ থেকে শুরু হচ্ছে",
      "Choose a ride" : "একটি রাইড চয়ন করুন",
    },
    'en_Indonesiya': {
      "Captains are busy" : "Kapten sedang sibuk",
      "Find a driver" : "Temukan pengemudi",
      "City to city" : "Kota ke kota",
      "From" : "Dari",
      "To" : "Ke",
      "Departure date" : "Tanggal keberangkatan",
      "Departure time" : "Waktu keberangkatan",
      "Done" : "Selesai",
      "Skip" : "Lewati",
      "Next" : "Berikutnya",
      "When" : "Kapan",
      "Number of passengers" : "Jumlah penumpang",
      "Set your price" : "Tetapkan harga Anda",
      "We charge no commission. Full" : "Kami tidak mengenakan komisi. Jumlah ",
      "amount goes to the captain" : "penuh masuk ke kapten",
      "Higher the price,higher the chance of" : "Semakin tinggi harga, semakin tinggi peluang",
      "getting a ride" : "mendapatkan tumpangan",
      "Automatically accept the nearest driver for your fare" : "Secara otomatis menerima pengemudi terdekat untuk tarif Anda",
      "Offer your fare" : "Tawarkan tarif Anda",
      "Comments" : "Komentar",
      "How many of you will go?" : "Berapa banyak dari Anda yang akan pergi?",
      "Captain on the way" : "Kapten sedang dalam perjalanan",
      "Captain has arrived" : "Kapten telah tiba",
      "Heading to the destination" : "Menuju tujuan",
      "Start your order with PIN" : "Mulai pesanan Anda dengan PIN",
      "Pickup From" : "Penjemputan Dari",
      "Trip Details" : "Detail Perjalanan",
      "Rating" : "Peringkat",
      "Trips" : "Perjalanan",
      "Joined" : "Bergabung",
      "Language" : "Bahasa",
      "Preference" : "Preferensi",
      "Choose a driver" : "Pilih pengemudi",
      "Driver can offer their fare and time" : "Pengemudi dapat menawarkan tarif dan waktu mereka",
      "Decline" : "Tolak",
      "Accept" : "Terima",
      "Drop to" : "Buka",
      "Faq List" : "Daftar Tanya Jawab",
      "CONTINUE" : "LANJUTKAN",
      "Payment Getway Method" : "Metode Pembayaran Getway",
      "All coupons" : "Semua kupon",
      "Best Coupon" : "Kupon Terbaik",
      "Coupon Code: " : "Kode Kupon:",
      "Coupon Amount: " : "Jumlah Kupon:",
      "Minimum Amount: " : "Jumlah Minimum:",
      "Ex Date: " : "Tanggal Ex:",
      "Remove" : "Hapus",
      "Apply coupons" : "Terapkan kupon",
      "Coupon" : "Kupon",
      "Coupon applied" : "Kupon diterapkan",
      "Try Again" : "Coba Lagi",
      "Cancel" : "Batal",
      "Home" : "Beranda",
      "My Ride" : "Perjalanan Saya",
      "Wallet" : "Dompet",
      "Profile" : "Profil",
      "Faq" : "Tanya Jawab",
      "Refer and earn" : "Referensi dan dapatkan penghasilan",
      "Notifications" : "Pemberitahuan",
      "Your Current Location" : "Lokasi Anda Saat Ini",
      "Close" : "Tutup",
      "Searching for you on the map..." : "Mencari Anda di peta...",
      "💡Raise the fare, increase your chances." : "💡Naikkan tarif, tingkatkan peluang Anda.",
      "Automatically book the nearest driver for" : "Pesan pengemudi terdekat secara otomatis untuk",
      "Cancel Request" : "Batalkan Permintaan",
      "cancel" : "Batal",
      "Completed" : "Selesai",
      "Invoice" : "Faktur",
      "Rate your ride" : "Beri peringkat perjalanan Anda",
      "Pickup" : "Penjemputan",
      "Destination" : "Tujuan",
      "RIDE DETAIL" : "DETAIL PERJALANAN",
      "Ride Type :" : "Jenis Perjalanan",
      "Car Type :" : "Jenis Mobil",
      "hours / minit :" : "jam / menit",
      "Date & Time :" : "Tanggal & Waktu",
      "PAYMENT" : "PEMBAYARAN",
      "Ride Fair :" : "Pameran Perjalanan",
      "Promo :" : "Promo :",
      "PlatformFee :" : "Biaya Platform :",
      "Weather Price :" : "Harga Cuaca :",
      "Total :" : "Total :",
      "My Rides" : "Perjalanan Saya",
      "Upcoming" : "Mendatang",
      "Cancelled" : "Dibatalkan",
      "Notification" : "Pemberitahuan",
      "No new notifications" : "Tidak ada pemberitahuan baru",
      "Looks like you haven't received any notification" : "Sepertinya Anda belum menerima pemberitahuan apa pun",
      "Allow Notifications and on-ride alerts" : "Izinkan Pemberitahuan dan peringatan perjalanan",
      "Real-time Captain updates" : "Pembaruan Kapten secara real-time",
      "Get notified about captain`s allocation, arrival and more" : "Dapatkan pemberitahuan tentang alokasi kapten, kedatangan, dan lainnya",
      "Be the first to know about our offers and new features" : "Jadilah yang pertama mengetahui tentang penawaran dan fitur baru kami",
      "Allow" : "Izinkan",
      "Maybe, later" : "Mungkin, nanti",
      "Location permission not enabled" : "Izin lokasi tidak diaktifkan",
      "Sharing Location permission helps us improve your ride booking and pickup experience" : "Berbagi izin Lokasi membantu kami meningkatkan pengalaman pemesanan dan penjemputan perjalanan Anda",
      "Allow Permission" : "Izinkan Izin",
      "Enter pickup manually" : "Masukkan penjemputan secara manual",
      "Drop" : "Jatuhkan",
      "Drop location" : "Lokasi penurunan",
      "Select on map" : "Pilih di peta",
      "Add a destination" : "Tambahkan tujuan",
      "Update" : "Perbarui",
      "My Profile" : "Profil Saya",
      "Name" : "Nama",
      "Email" : "Email",
      "Password" : "Kata Sandi",
      "Refer your friends" : "Rekomendasikan teman Anda",
      "& Earn Coins!" : "& Dapatkan Koin!",
      "Invite all your friend to " : "Undang semua teman Anda ke",
      "ZippyGo" : "ZippyGo",
      "Your referred person gets " : "Orang yang Anda referensikan akan mendapatkan",
      "coins when they sign up using your code" : "koin saat mereka mendaftar menggunakan kode Anda",
      "and you receive " : "dan Anda akan menerima",
      "coins when the person you referred purchases a membership." : "koin saat orang yang Anda referensikan membeli keanggotaan.",
      "Start inviting friends today and enjoy the benefits together!" : "Mulai undang teman hari ini dan nikmati manfaatnya bersama!",
      "Refer a Friend" : "Rekomendasikan Teman",
      "Help" : "Bantuan",
      "H" : "H",
      "RIDE COMPLETED" : "PERJALANAN SELESAI",
      "Select a payment method to pay" : "Pilih metode pembayaran untuk membayar",
      "Total trip fare" : "Total biaya perjalanan",
      "Ride Charges" : "Biaya perjalanan",
      "Discount" : "Diskon",
      "Whether Charge" : "Biaya yang dikenakan",
      "Platform fee" : "Biaya platform",
      "AMOUNT TO BE PAID" : "JUMLAH YANG HARUS DIBAYARKAN",
      "Payment Gateway Method" : "Metode Gerbang Pembayaran",
      "Total Balance" : "Total Saldo",
      "Add Wallet Amount" : "Tambah Jumlah Dompet",
      "Enter Amount" : "Masukkan Jumlah",
      "Select Payment Method" : "Pilih Metode Pembayaran",
      "Enter Amount!!!" : "Masukkan Jumlah!!!",
      "Top-up" : "Isi ulang",
      "Join Our App and Make a Difference:" : "Bergabunglah dengan Aplikasi Kami dan Buat Perubahan:",
      "Donate Today!" : "Donasi Hari Ini!",
      "Invite friend" : "Undang teman",
      "Transaction History" : "Riwayat Transaksi",
      "Debit" : "Debit",
      "Creadit" : "Kredit",
      "Welcome to Your ZippyGo Ride!" : "Selamat Datang di ZippyGo Ride Anda!",
      "Your Journey, Just a Tap Away" : "Perjalanan Anda, Cukup dengan Satu Ketukan",
      "Wherever You Go, We’re Here" : "Ke Mana Pun Anda Pergi, Kami Siap Melayani",
      "Book a ride in just a few taps and reach your destination comfortably" : "Pesan perjalanan hanya dengan beberapa ketukan dan capai tujuan Anda dengan nyaman",
      "Experience fast, reliable, and safe rides with ease." : "Rasakan perjalanan yang cepat, andal, dan aman dengan mudah.",
      "Find a ride quickly and enjoy your journey hassle-free" : "Temukan perjalanan dengan cepat dan nikmati perjalanan Anda tanpa repot",
      "Phone Number" : "Nomor Telepon",
      "By clicking Continue.you agree tp our " : "Dengan mengklik Lanjutkan, Anda setuju dengan",
      "T&Cs" : "Syarat & Ketentuan",
      "Continue" : "Lanjutkan",
      "Forget Password ?" : "Lupa Kata Sandi?",
      "Enter Mobile Number...!!!" : "Masukkan Nomor Ponsel...!!!",
      "Forgot Password ?" : "Lupa Kata Sandi?",
      "Milk made modern!" : "Susu dibuat modern!",
      "Our app combines the convenience of technology with the tradition of the milkman" : "Aplikasi kami menggabungkan kemudahan teknologi dengan tradisi tukang susu",
      "Never miss a delivery again!" : "Jangan pernah melewatkan pengiriman lagi!",
      "With our app, you'll receive real-time notifications about your milk deliveries" : "Dengan aplikasi kami, Anda akan menerima pemberitahuan waktu nyata tentang pengiriman susu Anda",
      "Milk at your fingertips!" : "Susu di ujung jari Anda!",
      "order fresh milk and dairy products for delivery straight to your doorstep" : "pesan susu segar dan produk olahan susu untuk dikirim langsung ke depan pintu Anda",
      "Get Started" : "Mulai",
      "Step 1/3" : "Langkah 1/3",
      "Let's get you trip-ready!" : "Mari kita persiapkan perjalanan Anda!",
      "Step 1/2" : "Langkah 1/2",
      "Got an OTP?" : "Sudah mendapatkan OTP?",
      "Step 2/2" : "Langkah 2/2",
      "Just one last thing" : "Satu hal lagi",
      "Full Name" : "Nama Lengkap",
      "email" : "Email",
      "Referral code(optional)" : "Kode rujukan (opsional)",
      "Referral code" : "Kode rujukan",
      "Let's go!" : "Ayo!",
      "No Chat Found!" : "Tidak Ada Obrolan Ditemukan!",
      "Currently you don’t have chat." : "Saat ini Anda tidak memiliki obrolan.",
      "Say Something..." : "Katakan Sesuatu...",
      "Reject" : "Tolak",
      "How much time do you need?" : "Berapa lama waktu yang Anda perlukan?",
      "Leave now" : "Berangkat sekarang",
      "Leave later" : "Berangkat nanti",
      "Date and Time" : "Tanggal dan Waktu",
      "Starting at" : "Mulai dari",
      "Choose a ride" : "Pilih perjalanan",
    }
  };
}