// ignore_for_file: file_names

import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_English': {
          "Captains are busy": "Captains are busy",
          "Find a driver": "Find a driver",
          "City to city": "City to city",
          "From": "From",
          "To": "To",
          "Departure date": "Departure date",
          "Departure time": "Departure time",
          "Done": "Done",
          "Skip": "Skip",
          "Next": "Next",
          "When": "When",
          "Number of passengers": "Number of passengers",
          "Set your price": "Set your price",
          "We charge no commission. Full": "We charge no commission. Full",
          "amount goes to the captain": "amount goes to the captain",
          "Higher the price,higher the chance of":
              "Higher the price,higher the chance of",
          "getting a ride": "getting a ride",
          "Automatically accept the nearest driver for your fare":
              "Automatically accept the nearest driver for your fare",
          "Offer your fare": "Offer your fare",
          "Comments": "Comments",
          "How many of you will go?": "How many of you will go?",
          "Captain on the way": "Captain on the way",
          "Captain has arrived": "Captain has arrived",
          "Heading to the destination": "Heading to the destination",
          "Start your order with PIN": "Start your order with PIN",
          "Pickup From": "Pickup From",
          "Trip Details": "Trip Details",
          "Rating": "Rating",
          "Trips": "Trips",
          "Joined": "Joined",
          "Language": "Language",
          "Preference": "Preference",
          "Choose a driver": "Choose a driver",
          "Driver can offer their fare and time":
              "Driver can offer their fare and time",
          "Decline": "Decline",
          "Accept": "Accept",
          "Drop to": "Drop to",
          "Faq List": "Faq List",
          "CONTINUE": "CONTINUE",
          "Payment Getway Method": "Payment Getway Method",
          "All coupons": "All coupons",
          "Best Coupon": "Best Coupon",
          "Coupon Code: ": "Coupon Code: ",
          "Coupon Amount: ": "Coupon Amount: ",
          "Minimum Amount: ": "Minimum Amount: ",
          "Ex Date: ": "Ex Date: ",
          "Remove": "Remove",
          "Apply coupons": "Apply coupons",
          "Coupon": "Coupon",
          "Coupon applied": "Coupon applied",
          "Try Again": "Try Again",
          "Cancel": "Cancel",
          "Home": "Home",
          "My Ride": "My Ride",
          "Wallet": "Wallet",
          "Profile": "Profile",
          "Faq": "Faq",
          "Refer and earn": "Refer and earn",
          "Notifications": "Notifications",
          "Your Current Location": "Your Current Location",
          "Close": "Close",
          "Searching for you on the map...": "Searching for you on the map...",
          "💡Raise the fare, increase your chances.":
              "💡Raise the fare, increase your chances.",
          "Automatically book the nearest driver for":
              "Automatically book the nearest driver for",
          "Cancel Request": "Cancel Request",
          "cancel": "cancel",
          "Completed": "Completed",
          "Invoice": "Invoice",
          "Rate your ride": "Rate your ride",
          "Pickup": "Pickup",
          "Destination": "Destination",
          "RIDE DETAIL": "RIDE DETAIL",
          "Ride Type :": "Ride Type :",
          "Car Type :": "Car Type :",
          "hours / minit :": "hours / minit :",
          "Date & Time :": "Date & Time :",
          "PAYMENT": "PAYMENT",
          "Ride Fair :": "Ride Fair :",
          "Promo :": "Promo :",
          "PlatformFee :": "PlatformFee :",
          "Weather Price :": "Weather Price :",
          "Total :": "Total :",
          "My Rides": "My Rides",
          "Upcoming": "Upcoming",
          "Cancelled": "Cancelled",
          "Notification": "Notification",
          "No new notifications": "No new notifications",
          "Looks like you haven't received any notification":
              "Looks like you haven't received any notification",
          "Allow Notifications and on-ride alerts":
              "Allow Notifications and on-ride alerts",
          "Real-time Captain updates": "Real-time Captain updates",
          "Get notified about captain`s allocation, arrival and more":
              "Get notified about captain`s allocation, arrival and more",
          "Be the first to know about our offers and new features":
              "Be the first to know about our offers and new features",
          "Allow": "Allow",
          "Maybe, later": "Maybe, later",
          "Location permission not enabled": "Location permission not enabled",
          "Sharing Location permission helps us improve your ride booking and pickup experience":
              "Sharing Location permission helps us improve your ride booking and pickup experience",
          "Allow Permission": "Allow Permission",
          "Enter pickup manually": "Enter pickup manually",
          "Drop": "Drop",
          "Drop location": "Drop location",
          "Select on map": "Select on map",
          "Add a destination": "Add a destination",
          "Update": "Update",
          "My Profile": "My Profile",
          "Name": "Name",
          "Email": "Email",
          "Password": "Password",
          "Refer your friends": "Refer your friends",
          "& Earn Coins!": "& Earn Coins!",
          "Invite all your friend to ": "Invite all your friend to ",
          "Qareeb": "Qareeb",
          "Your referred person gets ": "Your referred person gets ",
          "coins when they sign up using your code":
              " coins when they sign up using your code",
          "and you receive ": "and you receive ",
          "coins when the person you referred purchases a membership.":
              " coins when the person you referred purchases a membership.",
          "Start inviting friends today and enjoy the benefits together!":
              "Start inviting friends today and enjoy the benefits together!",
          "Refer a Friend": "Refer a Friend",
          "Help": "Help",
          "H": "H",
          "RIDE COMPLETED": "RIDE COMPLETED",
          "Select a payment method to pay": "Select a payment method to pay",
          "Total trip fare": "Total trip fare",
          "Ride Charges": "Ride Charges",
          "Discount": "Discount",
          "Whether Charge": "Whether Charge",
          "Platform fee": "Platform fee",
          "AMOUNT TO BE PAID": "AMOUNT TO BE PAID",
          "Payment Gateway Method": "Payment Gateway Method",
          "Total Balance": "Total Balance",
          "Add Wallet Amount": "Add Wallet Amount",
          "Enter Amount": "Enter Amount",
          "Select Payment Method": "Select Payment Method",
          "Enter Amount!!!": "Enter Amount!!!",
          "Top-up": "Top-up",
          "Join Our App and Make a Difference:":
              "Join Our App and Make a Difference:",
          "Donate Today!": "Donate Today!",
          "Invite friend": "Invite friend",
          "Transaction History": "Transaction History",
          "Debit": "Debit",
          "Creadit": "Creadit",
          "Welcome to Your Qareeb Ride!": "Welcome to Your Qareeb Ride!",
          "Your Journey, Just a Tap Away": "Your Journey, Just a Tap Away",
          "Wherever You Go, We’re Here": "Wherever You Go, We’re Here",
          "Book a ride in just a few taps and reach your destination comfortably":
              "Book a ride in just a few taps and reach your destination comfortably",
          "Experience fast, reliable, and safe rides with ease.":
              "Experience fast, reliable, and safe rides with ease.",
          "Find a ride quickly and enjoy your journey hassle-free":
              "Find a ride quickly and enjoy your journey hassle-free",
          "Phone Number": "Phone Number",
          "By clicking Continue.you agree tp our ":
              "By clicking Continue.you agree tp our ",
          "T&Cs": "T&Cs",
          "Continue": "Continue",
          "Forget Password ?": "Forget Password ?",
          "Enter Mobile Number...!!!": "Enter Mobile Number...!!!",
          "Forgot Password ?": "Forgot Password ?",
          "Milk made modern!": "Milk made modern!",
          "Our app combines the convenience of technology with the tradition of the milkman":
              "Our app combines the convenience of technology with the tradition of the milkman",
          "Never miss a delivery again!": "Never miss a delivery again!",
          "With our app, you'll receive real-time notifications about your milk deliveries":
              "With our app, you'll receive real-time notifications about your milk deliveries",
          "Milk at your fingertips!": "Milk at your fingertips!",
          "order fresh milk and dairy products for delivery straight to your doorstep":
              "order fresh milk and dairy products for delivery straight to your doorstep",
          "Get Started": "Get Started",
          "Step 1/3": "Step 1/3",
          "Let's get you trip-ready!": "Let's get you trip-ready!",
          "Step 1/2": "Step 1/2",
          "Got an OTP?": "Got an OTP?",
          "Step 2/2": "Step 2/2",
          "Just one last thing": "Just one last thing",
          "Full Name": "Full Name",
          "email": "email",
          "Referral code(optional)": "Referral code(optional)",
          "Referral code": "Referral code",
          "Let's go!": "Let's go!",
          "No Chat Found!": "No Chat Found!",
          "Currently you don’t have chat.": "Currently you don’t have chat.",
          "Say Something...": "Say Something...",
          "Reject": "Reject",
          "How much time do you need?": "How much time do you need?",
          "Leave now": "Leave now",
          "Leave later": "Leave later",
          "Date and Time": "Date and Time",
          "Starting at": "Starting at",
          "Choose a ride": "Choose a ride",
          // "" : "",
        },
        'ur_arabic': {
          "Captains are busy": "القادة مشغولون",
          "Find a driver": "ابحث عن سائق",
          "City to city": "من مدينة إلى مدينة",
          "From": "من",
          "To": "إلى",
          "Departure date": "تاريخ المغادرة",
          "Departure time": "وقت المغادرة",
          "Done": "تم",
          "Skip": "تخطي",
          "Next": "التالي",
          "When": "متى",
          "Number of passengers": "عدد الركاب",
          "Set your price": "حدد السعر",
          "We charge no commission. Full": "لا نفرض أي عمولة. يذهب المبلغ",
          "amount goes to the captain": "الكامل إلى القائد",
          "Higher the price,higher the chance of":
              "كلما ارتفع السعر، زادت فرصة",
          "getting a ride": "الحصول على رحلة",
          "Automatically accept the nearest driver for your fare":
              "اقبل تلقائيًا أقرب سائق مقابل أجرة",
          "Offer your fare": "اعرض أجرة",
          "Comments": "التعليقات",
          "How many of you will go?": "كم منكم سيذهب؟",
          "Captain on the way": "الكابتن في الطريق",
          "Captain has arrived": "لقد وصل الكابتن",
          "Heading to the destination": "متجه إلى الوجهة",
          "Start your order with PIN":
              "ابدأ طلبك باستخدام رقم التعريف الشخصي (PIN)",
          "Pickup From": "الاستلام من",
          "Trip Details": "تفاصيل الرحلة",
          "Rating": "التقييم",
          "Trips": "الرحلات",
          "Joined": "تم الانضمام",
          "Language": "اللغة",
          "Preference": "التفضيل",
          "Choose a driver": "اختر سائقًا",
          "Driver can offer their fare and time": "يمكن للسائق تقديم أجرة ووقت",
          "Decline": "رفض",
          "Accept": "قبول",
          "Drop to": "إسقاط إلى",
          "Faq List": "قائمة الأسئلة الشائعة",
          "CONTINUE": "متابعة",
          "Payment Getway Method": "طريقة الدفع Getway",
          "All coupons": "جميع القسائم",
          "Best Coupon": "أفضل قسيمة",
          "Coupon Code: ": "رمز القسيمة:",
          "Coupon Amount: ": "مبلغ القسيمة:",
          "Minimum Amount: ": "الحد الأدنى للمبلغ:",
          "Ex Date: ": "تاريخ انتهاء الصلاحية:",
          "Remove": "إزالة",
          "Apply coupons": "تطبيق القسائم",
          "Coupon": "القسيمة",
          "Coupon applied": "القسيمة المطبقة",
          "Try Again": "حاول مرة أخرى",
          "Cancel": "إلغاء",
          "Home": "الصفحة الرئيسية",
          "My Ride": "رحلتي",
          "Wallet": "المحفظة",
          "Profile": "الملف الشخصي",
          "Faq": "الأسئلة الشائعة",
          "Refer and earn": "أحل واكسب",
          "Notifications": "الإشعارات",
          "Your Current Location": "موقعك الحالي",
          "Close": "إغلاق",
          "Searching for you on the map...": "البحث عنك على الخريطة...",
          "💡Raise the fare, increase your chances.":
              "💡ارفع الأجرة، وزد من فرصك.",
          "Automatically book the nearest driver for":
              "احجز تلقائيًا أقرب سائق لـ",
          "Cancel Request": "إلغاء الطلب",
          "cancel": "إلغاء",
          "Completed": "مكتمل",
          "Invoice": "الفاتورة",
          "Rate your ride": "قيم رحلتك",
          "Pickup": "الاستلام",
          "Destination": "الوجهة",
          "RIDE DETAIL": "تفاصيل الرحلة",
          "Ride Type :": "نوع الرحلة:",
          "Car Type :": "نوع السيارة:",
          "hours / minit :": "ساعات/دقائق:",
          "Date & Time :": "التاريخ والوقت:",
          "PAYMENT": "الدفع",
          "Ride Fair :": "معرض الرحلة:",
          "Promo :": "العرض الترويجي:",
          "PlatformFee :": "رسوم المنصة:",
          "Weather Price :": "سعر الطقس:",
          "Total :": "الإجمالي:",
          "My Rides": "رحلاتي",
          "Upcoming": "المقبلة",
          "Cancelled": "الملغاة",
          "Notification": "الإشعارات",
          "No new notifications": "لا توجد إشعارات جديدة",
          "Looks like you haven't received any notification":
              "يبدو أنك لم تتلق أي إشعارات",
          "Allow Notifications and on-ride alerts":
              "السماح بالإشعارات والتنبيهات أثناء الرحلة",
          "Real-time Captain updates": "تحديثات القبطان في الوقت الفعلي",
          "Get notified about captain`s allocation, arrival and more":
              "احصل على إشعارات حول تخصيص القبطان ووصوله والمزيد",
          "Be the first to know about our offers and new features":
              "كن أول من يعرف بعروضنا والميزات الجديدة",
          "Allow": "السماح",
          "Maybe, later": "ربما، لاحقًا",
          "Location permission not enabled": "إذن الموقع غير ممكّن",
          "Sharing Location permission helps us improve your ride booking and pickup experience":
              "مشاركة إذن الموقع يساعدنا في تحسين حجز رحلتك وتجربة الاستلام",
          "Allow Permission": "السماح بالإذن",
          "Enter pickup manually": "إدخال الاستلام يدويًا",
          "Drop": "التسليم",
          "Drop location": "موقع التسليم",
          "Select on map": "حدد على الخريطة",
          "Add a destination": "أضف وجهة",
          "Update": "تحديث",
          "My Profile": "My الملف الشخصي",
          "Name": "الاسم",
          "Email": "البريد الإلكتروني",
          "Password": "كلمة المرور",
          "Refer your friends": "أحل أصدقاءك",
          "& Earn Coins!": "& اربح عملات!",
          "Invite all your friend to ": "ادعُ جميع أصدقائك إلى",
          "Qareeb": "Qareeb",
          "Your referred person gets ": "يحصل الشخص الذي أحلته على",
          " coins when they sign up using your code":
              "عملات عند التسجيل باستخدام الكود الخاص بك",
          "and you receive ": "وتتلقى",
          " coins when the person you referred purchases a membership.":
              "عملات عندما يشتري الشخص الذي أحلته عضوية.",
          "Start inviting friends today and enjoy the benefits together!":
              "ابدأ في دعوة الأصدقاء اليوم واستمتع بالمزايا معًا!",
          "Refer a Friend": "أحل صديقًا",
          "Help": "المساعدة",
          "H": "H",
          "RIDE COMPLETED": "اكتملت الرحلة",
          "Select a payment method to pay": "حدد طريقة الدفع للدفع",
          "Total trip fare": "إجمالي أجرة الرحلة",
          "Ride Charges": "رسوم الرحلة",
          "Discount": "الخصم",
          "Whether Charge": "سواء كانت رسومًا",
          "Platform fee": "رسوم المنصة",
          "AMOUNT TO BE PAID": "المبلغ المطلوب دفعه",
          "Payment Gateway Method": "طريقة بوابة الدفع",
          "Total Balance": "إجمالي الرصيد",
          "Add Wallet Amount": "أضف مبلغ المحفظة",
          "Enter Amount": "أدخل المبلغ",
          "Select Payment Method": "حدد طريقة الدفع",
          "Enter Amount!!!": "أدخل المبلغ!!!",
          "Top-up": "إعادة الشحن",
          "Join Our App and Make a Difference:":
              "انضم إلى تطبيقنا وأحدث فرقًا:",
          "Donate Today!": "تبرع اليوم!",
          "Invite friend": "ادعُ صديقًا",
          "Transaction History": "سجل المعاملات",
          "Debit": "الخصم",
          "Creadit": "Creadit",
          "Welcome to Your Qareeb Ride!": "مرحبًا بك في رحلتك على Qareeb!",
          "Your Journey, Just a Tap Away": "رحلتك، بنقرة واحدة فقط",
          "Wherever You Go, We’re Here": "أينما ذهبت، نحن هنا",
          "Book a ride in just a few taps and reach your destination comfortably":
              "احجز رحلة ببضع نقرات فقط ووصل إلى وجهتك بشكل مريح",
          "Experience fast, reliable, and safe rides with ease.":
              "استمتع برحلات سريعة وموثوقة وآمنة بكل سهولة.",
          "Find a ride quickly and enjoy your journey hassle-free":
              "اعثر على رحلة بسرعة واستمتع برحلتك دون أي متاعب",
          "Phone Number": "رقم الهاتف",
          "By clicking Continue.you agree tp our ":
              "بالنقر فوق متابعة، فإنك توافق على",
          "T&Cs": "شروط وأحكامنا",
          "Continue": "متابعة",
          "Forget Password ?": "نسيت كلمة المرور؟",
          "Enter Mobile Number...!!!": "أدخل رقم الهاتف المحمول...!!!",
          "Forgot Password ?": "نسيت كلمة المرور؟",
          "Milk made modern!": "حليب عصري!",
          "Our app combines the convenience of technology with the tradition of the milkman":
              "يجمع تطبيقنا بين راحة التكنولوجيا وتقاليد بائع الحليب",
          "Never miss a delivery again!": "لا تفوت أي عملية توصيل مرة أخرى!",
          "With our app, you'll receive real-time notifications about your milk deliveries":
              "من خلال تطبيقنا، ستتلقى إشعارات في الوقت الفعلي حول عمليات توصيل الحليب الخاصة بك",
          "Milk at your fingertips!": "الحليب في متناول يدك!",
          "order fresh milk and dairy products for delivery straight to your doorstep":
              "اطلب الحليب الطازج ومنتجات الألبان للتوصيل مباشرة إلى باب منزلك",
          "Get Started": "ابدأ",
          "Step 1/3": "الخطوة 1/3",
          "Let's get you trip-ready!": "دعنا نجهزك للرحلة!",
          "Step 1/2": "الخطوة 1/2",
          "Got an OTP?": "هل لديك كلمة مرور لمرة واحدة؟",
          "Step 2/2": "الخطوة 2/2",
          "Just one last thing": "شيء أخير",
          "Full Name": "الاسم الكامل",
          "email": "البريد الإلكتروني",
          "Referral code(optional)": "رمز الإحالة (اختياري)",
          "Referral code": "رمز الإحالة",
          "Let's go!": "لننطلق!",
          "No Chat Found!": "لم يتم العثور على دردشة!",
          "Currently you don’t have chat.": "حاليًا ليس لديك دردشة.",
          "Say Something...": "قل شيئًا...",
          "Reject": "ارفض",
          "How much time do you need?": "كم من الوقت تحتاج؟",
          "Leave now": "اغادر الآن",
          "Leave later": "اغادر لاحقًا",
          "Date and Time": "التاريخ والوقت",
          "Starting at": "يبدأ من",
          "Choose a ride": "اختر رحلة",
        }
      };
}
