// ignore_for_file: file_names

import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_English': {
          "Captains are busy": "Captains are busy",
          "Find a driver": "Find a driver",
          "City to city": "City to city",
          "From": "From",
          "To": "To",
          "Departure date": "Departure date",
          "Departure time": "Departure time",
          "Done": "Done",
          "Skip": "Skip",
          "Next": "Next",
          "When": "When",
          "Number of passengers": "Number of passengers",
          "Set your price": "Set your price",
          "We charge no commission. Full": "We charge no commission. Full",
          "amount goes to the captain": "amount goes to the captain",
          "Higher the price,higher the chance of":
              "Higher the price,higher the chance of",
          "getting a ride": "getting a ride",
          "Automatically accept the nearest driver for your fare":
              "Automatically accept the nearest driver for your fare",
          "Offer your fare": "Offer your fare",
          "Comments": "Comments",
          "How many of you will go?": "How many of you will go?",
          "Captain on the way": "Captain on the way",
          "Select Pickup and Drop": "Select Pickup and Drop",
          "Address is not in the zone!": "Address is not in the zone!",
          "Captain has arrived": "Captain has arrived",
          "Heading to the destination": "Heading to the destination",
          "Start your order with PIN": "Start your order with PIN",
          "Pickup From": "Pickup From",
          "Trip Details": "Trip Details",
          "Rating": "Rating",
          "Trips": "Trips",
          "Joined": "Joined",
          "Language": "Language",
          "Preference": "Preference",
          "Choose a driver": "Choose a driver",
          "Driver can offer their fare and time":
              "Driver can offer their fare and time",
          "Decline": "Decline",
          "Accept": "Accept",
          "Drop to": "Drop to",
          "Faq List": "Faq List",
          "CONTINUE": "CONTINUE",
          "Payment Getway Method": "Payment Getway Method",
          "All coupons": "All coupons",
          "Best Coupon": "Best Coupon",
          "Coupon Code: ": "Coupon Code: ",
          "Coupon Amount: ": "Coupon Amount: ",
          "Minimum Amount: ": "Minimum Amount: ",
          "Ex Date: ": "Ex Date: ",
          "Remove": "Remove",
          "Apply coupons": "Apply coupons",
          "Coupon": "Coupon",
          "Coupon applied": "Coupon applied",
          "Try Again": "Try Again",
          "Cancel": "Cancel",
          "Home": "Home",
          "My Ride": "My Ride",
          "Wallet": "Wallet",
          "Profile": "Profile",
          "Faq": "Faq",
          "Refer and earn": "Refer and earn",
          "Notifications": "Notifications",
          "Your Current Location": "Your Current Location",
          "Close": "Close",
          "Searching for you on the map...": "Searching for you on the map...",
          "💡Raise the fare, increase your chances.":
              "💡Raise the fare, increase your chances.",
          "Automatically book the nearest driver for":
              "Automatically book the nearest driver for",
          "Cancel Request": "Cancel Request",
          "cancel": "cancel",
          "Completed": "Completed",
          "Invoice": "Invoice",
          "Rate your ride": "Rate your ride",
          "Pickup": "Pickup",
          "Destination": "Destination",
          "RIDE DETAIL": "RIDE DETAIL",
          "Ride Type :": "Ride Type :",
          "Car Type :": "Car Type :",
          "hours / minit :": "hours / minit :",
          "Date & Time :": "Date & Time :",
          "PAYMENT": "PAYMENT",
          "Ride Fair :": "Ride Fair :",
          "Promo :": "Promo :",
          "PlatformFee :": "PlatformFee :",
          "Weather Price :": "Weather Price :",
          "Total :": "Total :",
          "My Rides": "My Rides",
          "Upcoming": "Upcoming",
          "Cancelled": "Cancelled",
          "Notification": "Notification",
          "No new notifications": "No new notifications",
          "Looks like you haven't received any notification":
              "Looks like you haven't received any notification",
          "Allow Notifications and on-ride alerts":
              "Allow Notifications and on-ride alerts",
          "Real-time Captain updates": "Real-time Captain updates",
          "Get notified about captain`s allocation, arrival and more":
              "Get notified about captain`s allocation, arrival and more",
          "Be the first to know about our offers and new features":
              "Be the first to know about our offers and new features",
          "Allow": "Allow",
          "Maybe, later": "Maybe, later",
          "Location permission not enabled": "Location permission not enabled",
          "Sharing Location permission helps us improve your ride booking and pickup experience":
              "Sharing Location permission helps us improve your ride booking and pickup experience",
          "Allow Permission": "Allow Permission",
          "Enter pickup manually": "Enter pickup manually",
          "Drop": "Drop",
          "Drop location": "Drop location",
          "Select on map": "Select on map",
          "Add a destination": "Add a destination",
          "Update": "Update",
          "My Profile": "My Profile",
          "Name": "Name",
          "Email": "Email",
          "Password": "Password",
          "Refer your friends": "Refer your friends",
          "& Earn Coins!": "& Earn Coins!",
          "Invite all your friend to ": "Invite all your friend to ",
          "Qareeb": "Qareeb",
          "Your referred person gets ": "Your referred person gets ",
          "coins when they sign up using your code":
              " coins when they sign up using your code",
          "and you receive ": "and you receive ",
          "coins when the person you referred purchases a membership.":
              " coins when the person you referred purchases a membership.",
          "Start inviting friends today and enjoy the benefits together!":
              "Start inviting friends today and enjoy the benefits together!",
          "Refer a Friend": "Refer a Friend",
          "Help": "Help",
          "H": "H",
          "RIDE COMPLETED": "RIDE COMPLETED",
          "Select a payment method to pay": "Select a payment method to pay",
          "Total trip fare": "Total trip fare",
          "Ride Charges": "Ride Charges",
          "Discount": "Discount",
          "Whether Charge": "Whether Charge",
          "Platform fee": "Platform fee",
          "AMOUNT TO BE PAID": "AMOUNT TO BE PAID",
          "Payment Gateway Method": "Payment Gateway Method",
          "Total Balance": "Total Balance",
          "Add Wallet Amount": "Add Wallet Amount",
          "Enter Amount": "Enter Amount",
          "Select Payment Method": "Select Payment Method",
          "Enter Amount!!!": "Enter Amount!!!",
          "Top-up": "Top-up",
          "Join Our App and Make a Difference:":
              "Join Our App and Make a Difference:",
          "Donate Today!": "Donate Today!",
          "Invite friend": "Invite friend",
          "Transaction History": "Transaction History",
          "Debit": "Debit",
          "Creadit": "Creadit",
          "Welcome to Your Qareeb Ride!": "Welcome to Your Qareeb Ride!",
          "Your Journey, Just a Tap Away": "Your Journey, Just a Tap Away",
          "Wherever You Go, We’re Here": "Wherever You Go, We’re Here",
          "Book a ride in just a few taps and reach your destination comfortably":
              "Book a ride in just a few taps and reach your destination comfortably",
          "Experience fast, reliable, and safe rides with ease.":
              "Experience fast, reliable, and safe rides with ease.",
          "Find a ride quickly and enjoy your journey hassle-free":
              "Find a ride quickly and enjoy your journey hassle-free",
          "Phone Number": "Phone Number",
          "By clicking Continue.you agree tp our ":
              "By clicking Continue.you agree tp our ",
          "T&Cs": "T&Cs",
          "Continue": "Continue",
          "Forget Password ?": "Forget Password ?",
          "Enter Mobile Number...!!!": "Enter Mobile Number...!!!",
          "Forgot Password ?": "Forgot Password ?",
          "Milk made modern!": "Milk made modern!",
          "Our app combines the convenience of technology with the tradition of the milkman":
              "Our app combines the convenience of technology with the tradition of the milkman",
          "Never miss a delivery again!": "Never miss a delivery again!",
          "With our app, you'll receive real-time notifications about your milk deliveries":
              "With our app, you'll receive real-time notifications about your milk deliveries",
          "Milk at your fingertips!": "Milk at your fingertips!",
          "order fresh milk and dairy products for delivery straight to your doorstep":
              "order fresh milk and dairy products for delivery straight to your doorstep",
          "Get Started": "Get Started",
          "Step 1/3": "Step 1/3",
          "Let's get you trip-ready!": "Let's get you trip-ready!",
          "Step 1/2": "Step 1/2",
          "Got an OTP?": "Got an OTP?",
          "Step 2/2": "Step 2/2",
          "Just one last thing": "Just one last thing",
          "Full Name": "Full Name",
          "email": "email",
          "Referral code(optional)": "Referral code(optional)",
          "Referral code": "Referral code",
          "Let's go!": "Let's go!",
          "No Chat Found!": "No Chat Found!",
          "Currently you don’t have chat.": "Currently you don’t have chat.",
          "Say Something...": "Say Something...",
          "Reject": "Reject",
          "How much time do you need?": "How much time do you need?",
          "Leave now": "Leave now",
          "Leave later": "Leave later",
          "Date and Time": "Date and Time",
          "Starting at": "Starting at",
          "Choose a ride": "Choose a ride",
          "Loading...": "Loading...",
          "Please wait": "Please wait",
          "Success": "Success",
          "Error": "Error",
          "Warning": "Warning",
          "Info": "Info",
          "Searching": "Searching",
          "Processing": "Processing",
          "Payment successful": "Payment successful",
          "Payment failed": "Payment failed",
          "Request sent": "Request sent",
          "Driver found": "Driver found",
          "Trip started": "Trip started",
          "Trip completed": "Trip completed",
          "No internet connection": "No internet connection",
          "Something went wrong": "Something went wrong",
          "Try again": "Try again",
          "Confirm": "Confirm",
          "Yes": "Yes",
          "No": "No",
          "Save": "Save",
          "Edit": "Edit",
          "Delete": "Delete",
          "Back": "Back",
          "Profile updated successfully": "Profile updated successfully",
          "Failed to update profile": "Failed to update profile",
          "Select image": "Select image",
          "Camera": "Camera",
          "Gallery": "Gallery",
          "Permission denied": "Permission denied",
          "Location not found": "Location not found",
          "Driver on the way": "Driver on the way",
          "Estimated arrival": "Estimated arrival",
          "Contact driver": "Contact driver",
          "Cancel trip": "Cancel trip",
          "Trip in progress": "Trip in progress",
          "Wallet balance": "Wallet balance",
          "Add money": "Add money",
          "Transaction history": "Transaction history",
          "Insufficient balance": "Insufficient balance",
          "Payment method": "Payment method",
          "Select payment method": "Select payment method",
          "Cash": "Cash",
          "Card": "Card",
          "Dark Mode": "Dark Mode",
          "Ride fare": "Ride fare",
          "Total amount": "Total amount",
          "Booking confirmed": "Booking confirmed",
          "Booking cancelled": "Booking cancelled",
          "Driver assigned": "Driver assigned",
          "Searching for driver": "Searching for driver",
          "No drivers available": "No drivers available",
          "Request timeout": "Request timeout",
          "Invalid location": "Invalid location",
          "Please select pickup location": "Please select pickup location",
          "Please select drop location": "Please select drop location",
          "Pickup and drop locations cannot be same":
              "Pickup and drop locations cannot be same",
          "Enter your name": "Enter your name",
          "Enter your email": "Enter your email",
          "Enter your phone": "Enter your phone",
          "Enter valid email": "Enter valid email",
          "Enter valid phone": "Enter valid phone",
          "Password must be at least 6 characters":
              "Password must be at least 6 characters",
          "Passwords do not match": "Passwords do not match",
          "Account created successfully": "Account created successfully",
          "Failed to create account": "Failed to create account",
          "Login successful": "Login successful",
          "Invalid credentials": "Invalid credentials",
          "Logout": "Logout",
          "Are you sure you want to logout?":
              "Are you sure you want to logout?",
          "Dark mode": "Dark mode",
          "Light mode": "Light mode",
          "Change language": "Change language",
          "English": "English",
          "Arabic": "العربية",
          "Version": "Version",
          "About": "About",
          "Privacy policy": "Privacy policy",
          "Terms of service": "Terms of service",
          "Contact support": "Contact support",
          "FAQ": "FAQ",
          "Share app": "Share app",
          "Rate app": "Rate app",
          "Update available": "Update available",
          "Please update to continue": "Please update to continue",
          "Update now": "Update now",
          "Later": "Later",
          "Your current request is in progress. You can either wait for it to complete or cancel to perform this action.":
              "Your current request is in progress. You can either wait for it to complete or cancel to perform this action.",
          "Request cancelled": "Request cancelled",
          "Unable to cancel": "Unable to cancel",
          "Automatic booking enabled": "Automatic booking enabled",
          "Manual driver selection": "Manual driver selection",
          "Price updated": "Price updated",
          "Invalid price": "Invalid price",
          "Minimum fare": "Minimum fare",
          "Maximum fare": "Maximum fare",
          "Work": "Work",
          "Other": "Other",
          "Add location": "Add location",
          "Location saved": "Location saved",
          "Failed to save location": "Failed to save location",
          "Remove location": "Remove location",
          "Location removed": "Location removed",
          "Mark as read": "Mark as read",
          "Clear all": "Clear all",
          "Are you sure?": "Are you sure?",
          "No results found": "No results found",
          "Connection error": "Connection error",
          "Server error": "Server error",
          "WiFi": "WiFi",
          "Mobile Data": "Mobile Data",
          "Ethernet": "Ethernet",
          "No Connection": "No Connection",
          "Unknown": "Unknown",
          "Calculating Price": "Calculating Price",
          "Connected": "Connected",
          "Fetching fare for Calculation...":
              "Fetching fare for Calculation...",
          "Disconnected": "Disconnected",
          "No Internet Connection": "No Internet Connection",
          "Please check your internet connection and try again. Make sure you're connected to Wi-Fi or mobile data.":
              "Please check your internet connection and try again. Make sure you're connected to Wi-Fi or mobile data.",
          "Server Error": "Server Error",
          "We're having trouble connecting to our servers. Our team has been notified and is working on a fix.":
              "We're having trouble connecting to our servers. Our team has been notified and is working on a fix.",
          "Request Timeout": "Request Timeout",
          "The request is taking longer than expected. Please check your connection and try again.":
              "The request is taking longer than expected. Please check your connection and try again.",
          "No Data Available": "No Data Available",
          "There's no data to show right now. Please try again later or refresh to check for updates.":
              "There's no data to show right now. Please try again later or refresh to check for updates.",
          "Please wait while we fetch your data. This should only take a moment.":
              "Please wait while we fetch your data. This should only take a moment.",
          "Under Maintenance": "Under Maintenance",
          "We're currently performing maintenance to improve your experience. Please try again shortly.":
              "We're currently performing maintenance to improve your experience. Please try again shortly.",
          "Something Went Wrong": "Something Went Wrong",
          "We encountered an unexpected error. Please try again or contact support if the problem persists.":
              "We encountered an unexpected error. Please try again or contact support if the problem persists.",
          "Retry": "Retry",
          "Refresh": "Refresh",
          "Check Again": "Check Again",
          "Loading": "Loading",
          "No internet connection available. Please check your network and try again.":
              "No internet connection available. Please check your network and try again.",
          "Request timed out. Please check your connection and try again.":
              "Request timed out. Please check your connection and try again.",
          "API returned false result": "API returned false result",
          "API request failed": "API request failed",
          "Something went wrong! Please try again.":
              "Something went wrong! Please try again.",
          "Server error. Please try again later.":
              "Server error. Please try again later.",
          "Calculation Loading": "Calculation Loading",
          "Calculating fare for this vehicle...":
              "Calculating fare for this vehicle...",
          "Please change vehicle type": "Please change vehicle type",
        },
        'ur_arabic': {
          // Basic Navigation & Actions
          "Captains are busy": "القادة مشغولون",
          "Find a driver": "ابحث عن سائق",
          "City to city": "من مدينة إلى مدينة",
          "From": "من",
          "To": "إلى",
          "Done": "تم",
          "Skip": "تخطي",
          "Next": "التالي",
          "Continue": "متابعة",
          "Cancel": "إلغاء",
          "Close": "إغلاق",
          "Accept": "قبول",
          "Decline": "رفض",
          "Update": "تحديث",
          "Remove": "إزالة",
          "Add": "إضافة",
          "Select": "اختيار",
          "Change": "تغيير",
          "Apply": "تطبيق",
          "Save": "حفظ",
          "Edit": "تعديل",
          "Delete": "حذف",
          "Back": "رجوع",
          "Yes": "نعم",
          "No": "لا",
          "Confirm": "تأكيد",
          "OK": "موافق",
          "Try Again": "حاول مرة أخرى",
          "Retry": "إعادة المحاولة",

          // Date & Time
          "Departure date": "تاريخ المغادرة",
          "Departure time": "وقت المغادرة",
          "When": "متى",
          "Date and Time": "التاريخ والوقت",
          "Starting at": "يبدأ من",
          "Leave now": "اغادر الآن",
          "Leave later": "اغادر لاحقًا",
          "How much time do you need?": "كم من الوقت تحتاج؟",
          "Estimated arrival": "الوصول المتوقع",
          "Arrival time": "وقت الوصول",
          "Estimated time": "الوقت المقدر",
          "hours / minit :": "ساعات/دقائق:",
          "Date & Time :": "التاريخ والوقت:",
          "minutes": "دقائق",
          "hours": "ساعات",
          "days": "أيام",
          "weeks": "أسابيع",
          "months": "شهور",

          // Passengers & Pricing
          "Number of passengers": "عدد الركاب",
          "How many of you will go?": "كم منكم سيذهب؟",
          "Set your price": "حدد السعر",
          "Offer your fare": "اعرض أجرة",
          "We charge no commission. Full": "لا نفرض أي عمولة. يذهب المبلغ",
          "amount goes to the captain": "الكامل إلى القائد",
          "Higher the price,higher the chance of":
              "كلما ارتفع السعر، زادت فرصة",
          "getting a ride": "الحصول على رحلة",
          "Automatically accept the nearest driver for your fare":
              "اقبل تلقائيًا أقرب سائق مقابل أجرة",
          "💡Raise the fare, increase your chances.":
              "💡ارفع الأجرة، وزد من فرصك.",
          "Automatically book the nearest driver for":
              "احجز تلقائيًا أقرب سائق بــ",

          // Location & Map
          "Select Pickup and Drop": "اختر موقع النزول والاقلاع",
          "Pickup": "الاستلام",
          "Pickup From": "الاستلام من",
          "Destination": "الوجهة",
          "Drop": "التسليم",
          "Drop to": "إسقاط إلى",
          "Drop location": "موقع التسليم",
          "Address is not in the zone!": "الموقع ليس ضمن النطاق المتاح",
          "Your Current Location": "موقعك الحالي",
          "Current location": "الموقع الحالي",
          "Select on map": "حدد على الخريطة",
          "Add a destination": "أضف وجهة",
          "Please select pickup location": "يرجى اختيار موقع الانطلاق",
          "Please select drop location": "يرجى اختيار موقع الوصول",
          "Pickup and drop locations cannot be same":
              "لا يمكن أن يكون موقع الانطلاق والوصول متماثلين",
          "Enter pickup manually": "إدخال الاستلام يدويًا",
          "Location not found": "لم يتم العثور على الموقع",
          "Invalid location": "موقع غير صحيح",
          "Location permission not enabled": "إذن الموقع غير ممكّن",
          "Sharing Location permission helps us improve your ride booking and pickup experience":
              "مشاركة إذن الموقع يساعدنا في تحسين حجز رحلتك وتجربة الاستلام",
          "Allow Permission": "السماح بالإذن",
          "Searching for you on the map...": "البحث عنك على الخريطة...",
          "Route": "المسار",
          "Traffic": "الحركة المرورية",
          "Fastest route": "أسرع مسار",
          "Shortest route": "أقصر مسار",
          "Alternative route": "مسار بديل",

          // Trip Status & Flow
          "Captain on the way": "الكابتن في الطريق",
          "Driver on the way": "السائق في الطريق",
          "Captain has arrived": "لقد وصل الكابتن",
          "Heading to the destination": "متجه إلى الوجهة",
          "Start your order with PIN":
              "ابدأ طلبك باستخدام رقم التعريف الشخصي (PIN)",
          "Choose a driver": "اختر سائقًا",
          "Choose a ride": "اختر رحلة",
          "Driver can offer their fare and time": "يمكن للسائق تقديم أجرة ووقت",
          "Trip Details": "تفاصيل الرحلة",
          "RIDE DETAIL": "تفاصيل الرحلة",
          "Ride Type :": "نوع الرحلة:",
          "Car Type :": "نوع السيارة:",
          "Trip started": "بدأت الرحلة",
          "Trip completed": "اكتملت الرحلة",
          "Trip in progress": "الرحلة قيد التنفيذ",
          "RIDE COMPLETED": "اكتملت الرحلة",
          "Cancel Request": "إلغاء الطلب",
          "Cancel trip": "إلغاء الرحلة",
          "Request cancelled": "تم إلغاء الطلب",
          "Unable to cancel": "تعذر الإلغاء",
          "Driver assigned": "تم تعيين السائق",
          "Vehicle assigned": "تم تعيين المركبة",
          "Searching for driver": "جاري البحث عن سائق",
          "No drivers available": "لا يوجد سائقون متاحون",
          "Request timeout": "انتهت مهلة الطلب",

          // Driver Information
          "Driver name": "اسم السائق",
          "Driver rating": "تقييم السائق",
          "Vehicle number": "رقم المركبة",
          "Driver phone": "هاتف السائق",
          "Driver location": "موقع السائق",
          "Contact driver": "اتصل بالسائق",
          "Driver found": "تم العثور على سائق",
          "Driver arriving": "السائق قادم",

          // Payment & Pricing
          "PAYMENT": "الدفع",
          "Ride Fair :": "معرض الرحلة:",
          "Ride fare": "أجرة الرحلة",
          "Total fare": "إجمالي الأجرة",
          "Total amount": "المبلغ الإجمالي",
          "Final amount": "المبلغ النهائي",
          "Base fare": "الأجرة الأساسية",
          "Distance charge": "رسوم المسافة",
          "Time charge": "رسوم الوقت",
          "Service fee": "رسوم الخدمة",
          "Fare breakdown": "تفصيل الأجرة",
          "Minimum fare": "الحد الأدنى للأجرة",
          "Maximum fare": "الحد الأقصى للأجرة",
          "Promo :": "العرض الترويجي:",
          "PlatformFee :": "رسوم المنصة:",
          "Platform fee": "رسوم المنصة",
          "Weather Price :": "سعر الطقس:",
          "Whether Charge": "سواء كانت رسومًا",
          "Total :": "الإجمالي:",
          "Discount": "الخصم",
          "Total trip fare": "إجمالي أجرة الرحلة",
          "Ride Charges": "رسوم الرحلة",
          "AMOUNT TO BE PAID": "المبلغ المطلوب دفعه",
          "Select a payment method to pay": "حدد طريقة الدفع للدفع",
          "Payment Gateway Method": "طريقة بوابة الدفع",
          "Payment Getway Method": "طريقة الدفع Getway",
          "Payment method": "طريقة الدفع",
          "Select payment method": "اختر طريقة الدفع",
          "Select Payment Method": "حدد طريقة الدفع",
          "Cash": "نقداً",
          "Card": "بطاقة",
          "Payment successful": "تم الدفع بنجاح",
          "Payment failed": "فشل الدفع",
          "Payment pending": "الدفع معلق",
          "Price updated": "تم تحديث السعر",
          "Invalid price": "سعر غير صالح",

          // Coupons
          "All coupons": "جميع القسائم",
          "Best Coupon": "أفضل قسيمة",
          "Coupon Code: ": "رمز القسيمة:",
          "Coupon Amount: ": "مبلغ القسيمة:",
          "Minimum Amount: ": "الحد الأدنى للمبلغ:",
          "Ex Date: ": "تاريخ انتهاء الصلاحية:",
          "Apply coupons": "تطبيق القسائم",
          "Coupon": "القسيمة",
          "Coupon applied": "القسيمة المطبقة",

          // Wallet & Balance
          "Wallet": "المحفظة",
          "Total Balance": "إجمالي الرصيد",
          "Wallet balance": "رصيد المحفظة",
          "Add Wallet Amount": "أضف مبلغ المحفظة",
          "Add money": "إضافة رصيد",
          "Enter Amount": "أدخل المبلغ",
          "Enter Amount!!!": "أدخل المبلغ!!!",
          "Top-up": "إعادة الشحن",
          "Transaction History": "سجل المعاملات",
          "Transaction history": "سجل المعاملات",
          "Debit": "الخصم",
          "Creadit": "Creadit",
          "Insufficient balance": "رصيد غير كاف",

          // Profile & User
          "Profile": "الملف الشخصي",
          "My Profile": "الملف الشخصي",
          "Name": "الاسم",
          "Full Name": "الاسم الكامل",
          "Email": "البريد الإلكتروني",
          "email": "البريد الإلكتروني",
          "Password": "كلمة المرور",
          "Phone Number": "رقم الهاتف",
          "Referral code(optional)": "رمز الإحالة (اختياري)",
          "Referral code": "رمز الإحالة",
          "Enter your name": "أدخل اسمك",
          "Enter your email": "أدخل بريدك الإلكتروني",
          "Enter your phone": "أدخل رقم هاتفك",
          "Enter valid email": "أدخل بريدًا إلكترونيًا صالحًا",
          "Enter valid phone": "أدخل رقم هاتف صالحًا",
          "Password must be at least 6 characters":
              "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
          "Passwords do not match": "كلمتا المرور غير متطابقتين",
          "Profile updated successfully": "تم تحديث الملف الشخصي بنجاح",
          "Failed to update profile": "فشل تحديث الملف الشخصي",

          // Authentication
          "Account created successfully": "تم إنشاء الحساب بنجاح",
          "Failed to create account": "فشل إنشاء الحساب",
          "Login successful": "تم تسجيل الدخول بنجاح",
          "Invalid credentials": "بيانات اعتماد غير صالحة",
          "Logout": "تسجيل الخروج",
          "Are you sure you want to logout?":
              "هل أنت متأكد أنك تريد تسجيل الخروج؟",
          "By clicking Continue.you agree tp our ":
              "بالنقر فوق متابعة، فإنك توافق على",
          "T&Cs": "شروط وأحكامنا",
          "Forget Password ?": "نسيت كلمة المرور؟",
          "Forgot Password ?": "نسيت كلمة المرور؟",
          "Enter Mobile Number...!!!": "أدخل رقم الهاتف المحمول...!!!",
          "Got an OTP?": "هل لديك كلمة مرور لمرة واحدة؟",
          "Just one last thing": "شيء أخير",
          "Let's get you trip-ready!": "دعنا نجهزك للرحلة!",
          "Let's go!": "لننطلق!",

          // Main Navigation
          "Home": "الصفحة الرئيسية",
          "My Ride": "رحلتي",
          "My Rides": "رحلاتي",
          "Upcoming": "المقبلة",
          "Completed": "مكتمل",
          "Cancelled": "الملغاة",

          // Settings & Language
          "Language": "اللغة",
          "Choose your preferred language": "اختر لغتك المفضلة",
          "App will restart to apply language changes":
              "سيتم إعادة تشغيل التطبيق لتطبيق تغييرات اللغة",
          "Change language": "تغيير اللغة",
          "English": "English",
          "العربية": "العربية",
          "Dark mode": "الوضع الداكن",
          "Light mode": "الوضع الفاتح",
          "Dark Mode": "الوضع المظلم",
          "Preference": "التفضيل",

          // Notifications
          "Notification": "الإشعارات",
          "Notifications": "الإشعارات",
          "No new notifications": "لا توجد إشعارات جديدة",
          "Looks like you haven't received any notification":
              "يبدو أنك لم تتلق أي إشعارات",
          "Allow Notifications and on-ride alerts":
              "السماح بالإشعارات والتنبيهات أثناء الرحلة",
          "Real-time Captain updates": "تحديثات القبطان في الوقت الفعلي",
          "Get notified about captain`s allocation, arrival and more":
              "احصل على إشعارات حول تخصيص القبطان ووصوله والمزيد",
          "Be the first to know about our offers and new features":
              "كن أول من يعرف بعروضنا والميزات الجديدة",
          "Allow": "السماح",
          "Maybe, later": "ربما، لاحقًا",
          "Mark as read": "تعيين مقروء",
          "Clear all": "مسح الكل",

          // Refer & Earn
          "Refer and earn": "أحل واكسب",
          "Refer your friends": "أحل أصدقاءك",
          "& Earn Coins!": "& اربح عملات!",
          "Invite all your friend to ": "ادعُ جميع أصدقائك إلى",
          "Qareeb": "Qareeb",
          "Your referred person gets ": "يحصل الشخص الذي أحلته على",
          " coins when they sign up using your code":
              "عملات عند التسجيل باستخدام الكود الخاص بك",
          "and you receive ": "وتتلقى",
          " coins when the person you referred purchases a membership.":
              "عملات عندما يشتري الشخص الذي أحلته عضوية.",
          "Start inviting friends today and enjoy the benefits together!":
              "ابدأ في دعوة الأصدقاء اليوم واستمتع بالمزايا معًا!",
          "Refer a Friend": "أحل صديقًا",
          "Invite friend": "ادعُ صديقًا",

          // FAQ & Help
          "Faq": "الأسئلة الشائعة",
          "Faq List": "قائمة الأسئلة الشائعة",
          "FAQ": "الأسئلة الشائعة",
          "Help": "المساعدة",
          "H": "H",

          // Rating & Reviews
          "Rate your ride": "قيم رحلتك",
          "Rating": "التقييم",
          "Comments": "التعليقات",

          // Status Messages
          "Loading": "جاري التحميل",
          "Loading...": "جاري التحميل...",
          "Please wait": "يرجى الانتظار",
          "Searching": "جاري البحث",
          "Processing": "جاري المعالجة",
          "Connecting": "جاري الاتصال",
          "Connected": "متصل",
          "Disconnected": "غير متصل",
          "Success": "نجاح",
          "Error": "خطأ",
          "Warning": "تحذير",
          "Info": "معلومات",
          "Found": "تم العثور",
          "Failed": "فشل",
          "Something went wrong": "حدث خطأ ما",
          "Something went wrong! Please try again.":
              "حدث خطأ ما! يرجى المحاولة مرة أخرى.",

          // App Info & Updates
          "Version": "الإصدار",
          "About": "حول",
          "Privacy policy": "سياسة الخصوصية",
          "Terms of service": "شروط الخدمة",
          "Contact support": "اتصل بالدعم",
          "Share app": "مشاركة التطبيق",
          "Rate app": "قيّم التطبيق",
          "Update available": "يتوفر تحديث",
          "Please update to continue": "يرجى التحديث للمتابعة",
          "Update now": "حدّث الآن",
          "Later": "لاحقًا",

          // Onboarding
          "Welcome to Your Qareeb Ride!": "مرحبًا بك في رحلتك على Qareeb!",
          "Your Journey, Just a Tap Away": "رحلتك، بنقرة واحدة فقط",
          "Wherever You Go, We're Here": "أينما ذهبت، نحن هنا",
          "Book a ride in just a few taps and reach your destination comfortably":
              "احجز رحلة ببضع نقرات فقط ووصل إلى وجهتك بشكل مريح",
          "Experience fast, reliable, and safe rides with ease.":
              "استمتع برحلات سريعة وموثوقة وآمنة بكل سهولة.",
          "Find a ride quickly and enjoy your journey hassle-free":
              "اعثر على رحلة بسرعة واستمتع برحلتك دون أي متاعب",
          "Get Started": "ابدأ",
          "Step 1/3": "الخطوة 1/3",
          "Step 1/2": "الخطوة 1/2",
          "Step 2/2": "الخطوة 2/2",

          // Chat & Communication
          "No Chat Found!": "لم يتم العثور على دردشة!",
          "Currently you don't have chat.": "حاليًا ليس لديك دردشة.",
          "Say Something...": "قل شيئًا...",
          "Reject": "ارفض",

          // Error Handling & Network
          "No internet connection": "لا يوجد اتصال بالإنترنت",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Please check your internet connection and try again. Make sure you're connected to Wi-Fi or mobile data.":
              "يرجى فحص اتصال الإنترنت والمحاولة مرة أخرى. تأكد من الاتصال بالواي فاي أو بيانات الجوال.",
          "Server Error": "خطأ في الخادم",
          "Server error. Please try again later.":
              "خطأ في الخادم. يرجى المحاولة لاحقاً.",
          "We're having trouble connecting to our servers. Our team has been notified and is working on a fix.":
              "نواجه مشكلة في الاتصال بخوادمنا. تم إبلاغ فريقنا ويعمل على حل المشكلة.",
          "Request Timeout": "انتهت مهلة الطلب",
          "The request is taking longer than expected. Please check your connection and try again.":
              "يستغرق الطلب وقتاً أطول من المتوقع. يرجى فحص الاتصال والمحاولة مرة أخرى.",
          "Request timed out. Please check your connection and try again.":
              "انتهت مهلة الطلب. يرجى فحص الاتصال والمحاولة مرة أخرى.",
          "No Data Available": "لا توجد بيانات متاحة",
          "There's no data to show right now. Please try again later or refresh to check for updates.":
              "لا توجد بيانات للعرض حالياً. يرجى المحاولة لاحقاً أو التحديث للبحث عن تحديثات.",
          "Please wait while we fetch your data. This should only take a moment.":
              "يرجى الانتظار بينما نحضر بياناتك. يجب أن يستغرق هذا لحظة فقط.",
          "Under Maintenance": "تحت الصيانة",
          "We're currently performing maintenance to improve your experience. Please try again shortly.":
              "نقوم حالياً بصيانة لتحسين تجربتك. يرجى المحاولة قريباً.",
          "Something Went Wrong": "حدث خطأ ما",
          "We encountered an unexpected error. Please try again or contact support if the problem persists.":
              "واجهنا خطأ غير متوقع. يرجى المحاولة مرة أخرى أو الاتصال بالدعم إذا استمرت المشكلة.",
          "Connection lost": "انقطع الاتصال",
          "Connection error": "خطأ في الاتصال",
          "Service unavailable": "الخدمة غير متاحة",
          "API returned false result": "أرجع API نتيجة خاطئة",
          "API request failed": "فشل طلب API",
          "No internet connection available. Please check your network and try again.":
              "لا يوجد اتصال إنترنت متاح. يرجى فحص الشبكة والمحاولة مرة أخرى.",

          // Calculation & Pricing
          "Calculating Price": "جارٍ حساب السعر",
          "Calculation Loading": "جارٍ حساب الأجرة...",
          "Calculating fare for this vehicle...":
              "جارٍ حساب الأجرة لهذه المركبة",
          "Fetching fare for Calculation...":
              "استخراج السعر لهذا النوع من المركبات",
          "Please change vehicle type": "يرجى تغيير نوع المركبة أولاً",

          // General Form Validation
          "Please enter some text": "يرجى إدخال نص",
          "Are you sure?": "هل أنت متأكد؟",
          "No results found": "لم يتم العثور على نتائج",

          // App Features
          "Refresh": "تحديث",
          "Check Again": "تحقق مرة أخرى",
          "Booking confirmed": "تم تأكيد الحجز",
          "Booking cancelled": "تم إلغاء الحجز",
          "Request sent": "تم إرسال الطلب",
          "Automatic booking enabled": "تم تفعيل الحجز التلقائي",
          "Manual driver selection": "اختيار السائق يدويًا",
          "Your current request is in progress. You can either wait for it to complete or cancel to perform this action.":
              "يوجد طلب حالي قيد التنفيذ. يمكنك الانتظار حتى يكتمل أو الإلغاء لتنفيذ هذا الإجراء.",

          // Other Features
          "Work": "العمل",
          "Other": "أخرى",
          "Add location": "إضافة موقع",
          "Location saved": "تم حفظ الموقع",
          "Failed to save location": "فشل حفظ الموقع",
          "Remove location": "إزالة الموقع",
          "Location removed": "تمت إزالة الموقع",
          "Select image": "اختر صورة",
          "Camera": "الكاميرا",
          "Gallery": "المعرض",
          "Permission denied": "تم رفض الإذن",

          // Network Types (if needed)
          "WiFi": "واي فاي",
          "Mobile Data": "بيانات الجوال",
          "Ethernet": "إيثرنت",
          "No Connection": "لا يوجد اتصال",
          "Unknown": "غير معروف",

          // Additional Onboarding Text
          "start the adventure ": "ابدأ المغامرة ",
          "together with our ": "معاً مع تطبيقنا ",
          "app today!": "اليوم!",
          "Join Our App and Make a Difference:":
              "انضم إلى تطبيقنا وأحدث فرقًا:",
          "Donate Today!": "تبرع اليوم!",

          // Additional Labels
          "Invoice": "الفاتورة",
          "Trips": "الرحلات",
          "Joined": "تم الانضمام",
          "CONTINUE": "متابعة",

          // Unused/Legacy Milk App Text (if removing milk references)
          "Milk made modern!": "حليب عصري!",
          "Our app combines the convenience of technology with the tradition of the milkman":
              "يجمع تطبيقنا بين راحة التكنولوجيا وتقاليد بائع الحليب",
          "Never miss a delivery again!": "لا تفوت أي عملية توصيل مرة أخرى!",
          "With our app, you'll receive real-time notifications about your milk deliveries":
              "من خلال تطبيقنا، ستتلقى إشعارات في الوقت الفعلي حول عمليات توصيل الحليب الخاصة بك",
          "Milk at your fingertips!": "الحليب في متناول يدك!",
          "order fresh milk and dairy products for delivery straight to your doorstep":
              "اطلب الحليب الطازج ومنتجات الألبان للتوصيل مباشرة إلى باب منزلك",

          // PDF and Documents
          "PDF Preview": "معاينة PDF",

          // OTP and Authentication
          "Login using the OTP sent":
              "سجل الدخول باستخدام رمز التحقق المرسل إلى",
          "Resend code?": "إعادة إرسال الرمز؟",
          "Seconds": "ثانية",
          "Please Enter Otp.": "يرجى إدخال رمز التحقق.",
          "Incorrect OTP. Please try again.":
              "رمز التحقق غير صحيح. يرجى المحاولة مرة أخرى.",
          "VERIFY OTP": "تحقق من الرمز",
          "We have sent the OTP to": "لقد أرسلنا رمز التحقق إلى",
          "Awesome": "رائع",
          "Enter Password": "أدخل كلمة المرور",
          "All fields are required.": "جميع الحقول مطلوبة.",

          // Driver Selection & Actions
          "Choose Your Driver": "اختر السائقك",
          "Choose Required": "الاختيار مطلوب",
          "You must either accept a driver offer or cancel the request to continue.":
              "يجب عليك إما قبول عرض السائق أو إلغاء الطلب للمتابعة.",
          "Accept a driver offer or cancel to continue":
              "اقبل عرض سائق أو ألغِ للمتابعة",
          "Cancel Request?": "إلغاء الطلب؟",
          "Are you sure you want to cancel this ride request?":
              "هل أنت متأكد أنك تريد إلغاء طلب الرحلة هذا؟",
          "Message": "رسالة",

          "Something went Wrong....!!!": "حدث خطأ ما....!!!",
          "Connection Error": "خطأ في الاتصال",
          "Failed to create ride request. Would you like to try again?":
              "فشل في إنشاء طلب الرحلة. هل تريد المحاولة مرة أخرى؟",
          "An unexpected error occurred. Please try again.":
              "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
          "All fields are required": "جميع الحقول مطلوبة",
          "No Service": "لا توجد خدمة",
        }
      };
}
