name: qareeb
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  toastification: ^2.0.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  intl_phone_field: ^3.2.0
  otp_text_field: ^1.1.3
  permission_handler: ^11.2.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.1.1
  onesignal_flutter: ^5.2.5
  http: ^0.13.6  # Keep existing version
  geocoding: ^3.0.0
  google_place: ^0.4.7
  flutter_polyline_points: ^1.0.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.0.6
  socket_io_client: ^2.0.3+1
  razorpay_flutter: ^1.3.6
  lottie: ^2.7.0  # Compatible with http ^0.13.6
  package_info_plus: ^4.2.0
  share_plus: ^7.2.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  firebase_core: ^3.5.0
  pdf: ^3.10.4
  printing: ^5.13.3
  webview_flutter: ^4.9.0
  flutter_widget_from_html_core: ^0.15.2
  provider: ^6.1.1
  url_launcher: ^6.1.9
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  animate_do: ^3.3.4
  dio: ^5.8.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/
    - assets/map_styles/
    - assets/svgpicture/
    - assets/map_styles/dark_style.json

  fonts:
    - family: SofiaRegular
      fonts:
        - asset: assets/All_Fonts/Sofia Pro Regular.ttf
    - family: SofiaProLight
      fonts:
        - asset: assets/All_Fonts/SofiaProLight.ttf
    - family: SofiaProBold
      fonts:
        - asset: assets/All_Fonts/SofiaProBold.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/All_Fonts/Gilroy-Regular.otf
    - family: GilroyLight
      fonts:
        - asset: assets/All_Fonts/Gilroy-Light.ttf
    - family: GilroyBold
      fonts:
        - asset: assets/All_Fonts/Gilroy-Bold.ttf
    - family: Khebrat
      fonts:
        - asset: assets/All_Fonts/Khebrat/18 Khebrat Musamim Regular.ttf