// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFrMvEUaMdVJ9I50OdqKJqR7UcJmVZY0c',
    appId: '1:1048285519214:web:2c2d0085e55fbde4e3b57f',
    messagingSenderId: '1048285519214',
    projectId: 'qareeb-79bcf',
    authDomain: 'qareeb-79bcf.firebaseapp.com',
    storageBucket: 'qareeb-79bcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDproDOArrR57D0uFz8MeVaaGHXKlCP_Rs',
    appId: '1:1048285519214:android:fddb43968b7e65b2e3b57f',
    messagingSenderId: '1048285519214',
    projectId: 'qareeb-79bcf',
    storageBucket: 'qareeb-79bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDogSsISGA_ICtnLdLUht80VzBVSevekG0',
    appId: '1:1048285519214:ios:c3906d8b9a435850e3b57f',
    messagingSenderId: '1048285519214',
    projectId: 'qareeb-79bcf',
    storageBucket: 'qareeb-79bcf.firebasestorage.app',
    iosBundleId: 'com.qareeb.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '*************',
    appId: '****************',
    messagingSenderId: '******',
    projectId: '****-******',
    storageBucket: '*****-****.appspot.com',
    androidClientId: '**********',
    iosClientId: '**************',
    iosBundleId: 'com.qareeb.customer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '*************',
    appId: '*******',
    messagingSenderId: '************',
    projectId: '*******',
    authDomain: '******',
    storageBucket: '******-************.appspot.com',
  );
}